[2단계 미션] 김준수 미션 제출합니다!
cho-log/self-paced-react pull request #17
Opened 2024-10-08 02:19 UTC by gogo1414

### 개요
안녕하세요, 리뷰어님
이번 미션 진행은 어떠셨나요!? 1단계를 했다고 그런지 2단계는 조금 더 빨리 끝낼 수 있었네요!

### 호기심
`const [state, setState] = useState();`
`useState`를 활용하다보니 이게 생각외로 엄청 편한걸 알았어요 근데 살짝 궁금한 점이 생겼어요! `event` 발생이 일어났을 때 `setState` 내부의 값을 변경해주고, 다시 부모 값을 변경해주는 흐름이 맞을까요?? 제가 이해한게 맞는지 궁금하네요!
추가로, 함수형으로 파라미터를 사용해야 최신의 상태값을 유지할 수 있다고 하는데, 현재 제가 작성한 코드를 어떤식으로 바꿔야 좋아지는건지 알 수 있을까요??..

### 작업 내용
1. 레스토랑 리스트 `props`로 내려받기 구현
2. 카테고리 필터 기능 구현
3. index를 key로 적용하여 option 태그 에러문구 제거
4. 이미지 src 경로 변경 함수화

### Image
<img width="976" alt="스크린샷 2024-10-07 오후 8 37 30" src="https://github.com/user-attachments/assets/84c1b839-73fd-4e1b-9709-b6a7df72624e">

### Directory Structure
<img width="251" alt="스크린샷 2024-10-08 오전 11 17 25" src="https://github.com/user-attachments/assets/f8219025-e340-4543-b911-26ccca357f46">

### 느낀점
1. 점점 리액트에 대해 익숙해지고, 제가 적용한 것들이 화면에 실시간으로 반영된다는 점 때문에 너무 즐거워요😊
2. 아직까지 구현 기능에 급급해서 제가 사용하는 함수의 구체적인 흐름에 대해 파악하지 못하고 가는 점이 아쉽네요ㅜ

2024-10-09 17:33 UTC, Songhyejeong reviewed
안녕하세요 준수님! 

2단계 미션에서 리액트에 대해서 익숙해지고, 즐거움을 느끼셨다니 좋은 소식이네요! 👍 

이번에도 궁금하신 점에 대한 제 생각을 공유해보겠습니다!


1. useState의 동작원리에 대해
 이 질문을 제가 제대로 이해하지 못한 거 같아요 ,, 근데 아마 생각하고 계신게 맞으실 거 같아요!
 아마 공부 하시면서 이해하셨겠지만 setState는 setter 함수예요 
 `event` 발생이 일어났을 때 setter함수가 동작하여 state 변수를 갱신해줍니다! 그리고 새로운 category 변수를 App 컴포넌트에 넘기면서 리렌더링 된다 이 흐름대로 이해하셨다면 맞으실겁니다. 

2. 함수형 파라미터에 관해서
저도 useState 렌더링에 대해서 헷갈렸었는데 좋은 고민하고 갑니다!!
https://ko.react.dev/reference/react/useState
https://ko.react.dev/learn/state-as-a-snapshot

이 두개 참고하셔서 이해해보시면 좋을 거 같은데 저도 아직 정확하게 이해하고 있지 않아서 확실한 답은 못드릴 것 같지만 지금까지 이해한 걸 설명해드리면

useState는 다음 렌더링에 대해서만 변경 된다고 합니다.
<button onClick={() => {
  setNumber(number + 1);
  setNumber(number + 1);
  setNumber(number + 1);
}}>+3</button>
이 경우에, number는 1로 렌더링 될까요 3으로 렌더링 될까요?

<img width="837" alt="Screenshot 2024-10-10 at 2 27 02 AM" src="https://github.com/user-attachments/assets/456536a1-9e30-4fe9-9f31-8bf2fa3ba061">

여기서 React는 다음 렌더링에서 number를 0에서 1로 변경할 준비만 3번 하는 꼴이 됩니다. 
따라서, 1이 렌더링 되겠지요

지금 카테고리 같은 경우는, '직접' 값을 전달 하여도, 잘 렌더링 될 텐데 
그 이유는 settet함수가 한 번의 렌더링 과정에서 하나만 실행되니, 다음 렌더링에서 대기하고 있는 값이 하나밖에 없기 때문이 아닐까요?

확실하지 않은 답변인데, 준수님과 다른 리뷰어님의 생각도 궁금합니다..!

이번 주 미션 수고많으셨습니다 !~!

2024-10-09 17:33 UTC, Songhyejeong commented on src/App.jsx
> +  const filteredRestaurants = category === "전체" ? restaurantList : restaurantList.filter(
filter() 함수로 구현하는 방법이 있었네요 ! 👍

2024-10-09 17:33 UTC, Songhyejeong commented on src/App.jsx
> +  const filteredRestaurants = category === "전체" ? restaurantList : restaurantList.filter(
삼항 연산자까지 사용해주셨네요 ! 👍

2024-10-09 17:33 UTC, Songhyejeong commented on src/components/RestaurantList.jsx
> +function convertCategoryToImageSrc(category) {
👍

2024-10-09 17:33 UTC, Songhyejeong commented on src/components/RestaurantList.jsx
> +function convertCategoryToImageSrc(category) {
저는 이 부분이 판별하는 조건이 많아서 switch문을 사용하면 좋을 거 같다고 생각했는데
준수님의 의견도 궁금하네요! !

2024-10-09 17:33 UTC, Songhyejeong commented on src/components/CategoryFilter.jsx
> +                onChange={(event) => onChangeCategory(event.target.value)}
👍 👍

2024-10-10 02:26 UTC, gogo1414 commented on src/components/RestaurantList.jsx
> +function convertCategoryToImageSrc(category) {
`switch`문을 사용하는 방식도 좋을거 같아요
코드를 작성할 때 상대방에게 제 의도가 전달될 수 있다는 전제하에 본인이 선호하는 방향이 가장 좋은거 같아요!😊

2024-10-10 03:39 UTC, gogo1414 commented
> 이 질문을 제가 제대로 이해하지 못한 거 같아요 ,, 근데 아마 생각하고 계신게 맞으실 거 같아요!
아마 공부 하시면서 이해하셨겠지만 setState는 setter 함수예요
event 발생이 일어났을 때 setter함수가 동작하여 state 변수를 갱신해줍니다! 그리고 새로운 category 변수를 App 컴포넌트에 넘기면서 리렌더링 된다 이 흐름대로 이해하셨다면 맞으실겁니다. 👍

맞는 내용이라면 다행이네요! 저도 글을 보며 이해하다 보니 이해한 방향이 맞는지 궁금해서 여쭤봤어요! 감사합니다😊

> https://ko.react.dev/reference/react/useState
https://ko.react.dev/learn/state-as-a-snapshot
여기서 React는 다음 렌더링에서 number를 0에서 1로 변경할 준비만 3번 하는 꼴이 됩니다.
따라서, 1이 렌더링 되겠지요
지금 카테고리 같은 경우는, '직접' 값을 전달 하여도, 잘 렌더링 될 텐데
setter함수가 한 번의 렌더링 과정에서 위의 setNumber처럼 3개가 실행되지 않고 하나만 실행되니,
다음 렌더링에서 대기하고 있는 카테고리의 값이 하나밖에 없고
결국 이전 상태를 저장할 필요가 없겠죠?

이 부분은 약간 제가 명확하게 작성을 하지 않아서 잘못 이해하신거 같아요!
```
// A
<button onClick={() => {
  setNumber(number + 1);
  setNumber(number + 1);
  setNumber(number + 1);
}}>+3</button>
```
```
// B
<button onClick={() => {
  setNumber((number) => number + 1);
  setNumber((number) => number + 1);
  setNumber((number) => number + 1);
}}>+3</button>
```
A와 B를 보실 경우 A의 경우 혜정님이 말씀하신대로 0에서 항상 결과가 1로 나오지만, B의 경우에는 +3이 정상적으로 나와요! 이렇게 함수형 파라미터를 사용하게 될 경우 현재 상태 값이 아닌 변경된 가장 최근의 상태가 함수에 전달되어 계산이 정상적으로 이루어 지는 것으로 알고 있어요 그래서 이렇게 함수형 파라미터를 사용하는 것이 좋을 지 여쭤봤던거 였습니다!

2024-10-10 04:49 UTC, Songhyejeong commented
> A와 B를 보실 경우 A의 경우 혜정님이 말씀하신대로 0에서 항상 결과가 1로 나오지만, B의 경우에는 +3이 정상적으로 나와요! 이렇게 함수형 파라미터를 사용하게 될 경우 현재 상태 값이 아닌 변경된 가장 최근의 상태가 함수에 전달되어 계산이 정상적으로 이루어 지는 것으로 알고 있어요 그래서 이렇게 함수형 파라미터를 사용하는 것이 좋을 지 여쭤봤던거 였습니다!

제가 예시만 장황하게 설명 드리고, 함수형 파라미터를 적용해야할지에 대한 의견을 자세히 적지 못한 것 같네요,,
사실, 제가 전달 드리고자 했던 내용은 결론적으로, 이 코드에서는 함수형 파리미터를 쓰지 않고, 값을 직접 전달해도 괜찮을 것 같다는 의견이에요

```
//A
 <button onClick={() => {
  setNumber(number + 3);
  }}>+3</button>`

```

```
 // B
 <button onClick={() => {
   setNumber((number) => number + 1); //1
   setNumber((number) => number + 1); //2
   setNumber((number) => number + 1); //3
 }}>+3</button>
```

- A. setNumber가 한 번의 렌더링에서 1번의 호출이 있을 경우
- B. setNumber가 한 번의 렌더링에서 3번의 호출이 있을 경우


이 두가지 경우를 비교해서 생각해보시는 것이 좋을 거 같아요!  A는 정상 작동이 될 겁니다! 

A. 
(number) => number + 3은  다음 state로 3을 반환합니다.

B.
(number) => number + 1은 대기 중인 state로 0 받고 다음 state로 1을 반환합니다.
(number) => number + 1은 대기 중(가장 최근의 상태)인 state로 1을 받고 다음 state로 2를 반환합니다.
(number) => number + 1은 대기 중인(가장 최근의 상태) state로 2를 받고 다음 state로 3를 반환합니다.
그리고 다음 렌더링에서는 최종적으로 3이(가장 최근의 상태) 렌더링 합니다. 


제가 전달드리고 싶었던 내용은, setCategory인 setter함수가 한 번의 렌더링 과정에서 위의 
B의  setNumber처럼 3번이 호출 되지 않고 A 처럼 한 번만 호출되니, 

다음 렌더링에서 대기하고 있는 카테고리의 값이 하나밖에 없고 결국 가장 최근의 상태를 전달할 필요가 없을 것 같다는 내용이었어요!

예시가 적절한지 모르겠는데, 조금 더 찾아봐야 확실해질 거 같아요,, 일단은 이렇게 정리해봤습니다!

2024-10-10 05:56 UTC, gogo1414 commented
설명 너무 자세하게 해주셔서 바로 이해가 갔네요!
카테고리가 결국 선택되는건 1개만 선택되고 중복 선택이 되는 방식이 아니기 때문에 혜정님이 설명해주신 내용과 같이 함수형 파라미터를 적용하지 않아도 괜찮겠네요!!

감사합니다👍

2024-10-10 11:36 UTC, Indigochi1d commented on src/App.jsx
> +  const filteredRestaurants = category === "전체" ? restaurantList : restaurantList.filter(
삼항연산자와 filter함수를 통해 코드를 작성하셔서 읽기 편했습니다!

2024-10-10 12:16 UTC, Indigochi1d requested changes
안녕하세여 준수님~ step2는 어떠셨나요? 생각보다 할만한가요? 아마 해왔던 백엔드와는 달리 내가 코드를 적자마자 달라지는게 보이는 UI에 흥미를 느끼는 계기가 되지 않았을까 싶네요 ㅎㅎ

일단 전체적으로 코드는 잘 만드신 것 같아요. RestaurnatList.jsx 파일안에 Item까지 구현한것은 저도 조금 생각해봐야할 부분이 있네요🤔 export를 RestaurantList로만 하다보니 코드구조를 알기 전에는 RestaurantItem이 그 파일에 있는지 모를 수도 있다고 생각이 들기도 하면서 다른한편으로는 한 파일에 모아두니 한번에 보기 쉽다는 장점도 있는 것 같습니다! 이 부분은 저희 스터디때 멤버분들과 이야기 해보는 시간을 가지면 좋을 것 같아요.(인간교보재셔)

또, 혜정님과 state에 대해서 많은 토론을 거치셨는데 함수형파라미터와 일반 파라미터의 차이에 대해서 궁금해하실수 있을 것 같아요. 저도 처음 리액트를 공부했을 때 차이점을 찾곤 했었습니다. 왜 그런지 제 지식에 기반해서 설명해보도록 할게요.

## setState의 함수형 업데이트 방식
우선 setState는 **비동기**적 특성을 가집니다. 리액트가 효율적으로 렌더링하기 위해 여러 개의 상태 값 변경 요청을 batch(일괄 처리) 처리하기 때문이에요. setState가 여러번 호출되면 단일객체로 merge하려는 시도를 하는데 이것을 "오브젝트 컴포지션"이라고 부릅니다. setState는 상태를 바꾸는 것이고 "상태를 바꾼다"라는 것은 리렌더링을 필수적으로 일으킵니다. 근데 setState가 일어날때마다 리렌더링을 일으킨다고 생각해보면....setState를 성능적으로 사용하기 두려워질수도 있어요.

하지만 setState 를 동기적으로 사용하는 방법은 없을까요? 그게 바로 함수형 파라미터를 사용하는 방식입니다. 함수를 인자로 전달받은 `setNumber`는 원하는 시점의 상태를 가지고 업데이트를 해요. 객체가 아닌 함수형 `setNumber`가 호출되면 merge 할 객체가 없기 때문에 호출된 순서대로 함수를 큐에 넣습니다. 그 후에 큐의 각 함수를 호출하여 함수형 setNumber의 이전 상태를 전달하여 상태를 업데이트해요. 

주절주절 써서 이해가 되셨을지는 모르지만 도움이 되었으면 좋겠네유. 이번 주도 미션하느라 고생하셨구 함수형파라미터에 대한 주제는 중간고사 기간이 끝난후 스터디에서 이야기 해보도록 하죠 🤔  
수고하셨고 중간고사 화이팅입니다~

2024-10-10 12:16 UTC, Indigochi1d commented on src/App.jsx
> +        <RestaurantList restaurants={filteredRestaurants} />
props로 잘 넘겨주셨네요. 다만 한가지 제안드릴점은 onChageCategory props 이름을 setCategory로 바꾸는 것입니다! 지금은 props drilling이 생기지 않고 있지만 setCategory함수를 하위의 컴포넌트로 계속해서 넘겨야할때 onChangeCategory는 가독성이 떨어질수 있다고 생각해요. 준수님의 의견이 어떤지도 듣고 싶습니다.

> setCategory함수를 하위의 컴포넌트로 계속해서 넘겨야할때 onChangeCategory는 가독성이 떨어질수 있다고 생각해요.
이 말에 대한 예시는 아래에 그림으로 첨부할게요.
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/ba9fea89-43d8-4e23-9430-175e36bd28df">
Aside쪽을 보시면 setter함수가 계속해서 넘어가고 있는데 이런것을 props drilling이라고 불러요. 근데 준수님이 설정하신대로 onChangeCategory라는 이름으로 setter함수를 넘기게 되면 정작 setter함수를 실사용하는 하위컴포넌트에서 이 함수가 setter함수인지 헷갈릴 수 있다는 지점에서 말씀드립니다!

2024-10-10 12:16 UTC, Indigochi1d commented on src/components/AddRestaurantModal.jsx
> +}
카테고리를 map key로 선별하기 위해 id를 주는 방식으로 설정하셨군요!

2024-10-10 12:16 UTC, Indigochi1d commented on src/components/Category.jsx
이건 중복된 코드인걸까요?

2024-10-10 12:16 UTC, Indigochi1d commented on src/components/RestaurantList.jsx
> +            <img src={convertCategoryToImageSrc(category)} alt={alt} className={styles["category-icon"]}></img>
이미지를 import해오는 것이 아닌 경로를 설정하는 함수를 만듦으로써 경로를 설정하셨네요! 저는 일일히 이미지를 다 import 해왔는데 이게 코드 가독성 부분에서 더  나은 것 같아요😄

2024-10-11 02:50 UTC, gogo1414 commented on src/App.jsx
> +        <RestaurantList restaurants={filteredRestaurants} />
적어주신대로 컴포넌트 흐름도를 생각했을 때 하나의 명칭으로 통일되는 방식이 가독성 향상에도 좋은거 같아요!
좋은 리뷰 참고해서 반영하도록 하겠습니다!!

2024-10-11 02:51 UTC, gogo1414 commented on src/components/AddRestaurantModal.jsx
> +}
`index`에 대한 내용을 보고난 후 적용해보았습니다😊

2024-10-11 02:53 UTC, gogo1414 commented on src/components/Category.jsx
카테고리 데이터를 별도로 분리하고 있었는데, `AddRestaurantModal.jsx`안에 있는 함수를 지우고 `Category.jsx`를 사용하게 될거 같아요!
범수님이 1단계에서 적어주신 `data.js` 를 참고해서 다시 작성해보려구요!!

2024-10-13 23:46 UTC, Indigochi1d reviewed
수고하셨습니다!

2024-10-13 23:46 UTC, Indigochi1d commented on src/data/Restaurant.js
리뷰를 적용해서 따로 데이터를 분리해주셨군요!

2024-10-13 23:46 UTC, Indigochi1d commented on src/components/Main/RestaurantItem.jsx
> +}
Item과 List를 분리하셨네요 👍🏻

2024-10-14 08:01 UTC, merged