Step1
cho-log/self-paced-react pull request #18
Opened 2024-10-08 04:55 UTC by ye6194

2024-10-09 12:46 UTC, Indigochi1d reviewed
안녕하세요 예은님🫠

리액트를 사용해오시면서 이번 미션은 어땠는지 궁금하네요! PR을 읽어보니 초기세팅에 많은 어려움이 있으셨다고 하는데 아마 Vite환경설정에서 CRA환경설정으로 바꾸는 과정에서 생긴 문제일거에요. 

보통 Vite환경에서 React개발서버를 열때는 `npm run dev` 명령어를 사용해서 여는데
CRA에서의 `npm start` 를 사용하셨을때 앱이 켜지지 않아서 설정을 바꾸신건가? 아니면 다른 이유가 있는건가? 하고 생각하게 되었습니다..ㅎ 답변을 남겨주시면 감사하겠습니다 너무 궁금해요❗  

또 Component 흐름도를 작성해주셨는데 다음 미션부터는 props로 넘어가는 것들이 있을거에요. props로 넘어가는게 있다면 텍스트를 추가해 어떤 props가 넘어가는지 알려주세요!

2024-10-09 12:46 UTC, Indigochi1d commented on .eslintrc.cjs
> +  env: { browser: true, es2020: true, node: true },
CRA환경으로 설정할때 CRA는 개발 서버나 빌드도구로 react-scripts를 사용면서 Node환경을 다뤄요. 반면 Vite는 의존성을 최소화하는 방식을 채택하기 때문에 이 설정이 빠져있었습니다!
더 자세한 것을 알고 싶으시면 CRA와 Vite 의 차이를 더 찾아보시면 좋을 것 같아요!

2024-10-09 12:46 UTC, Indigochi1d commented on .eslintrc.cjs
> +  ignorePatterns: ["dist", ".eslintrc.cjs", "*.html"],
이것 또한 CRA와 Vite의 차이 때문에 발생합니다! CRA와 Vite에서의 HTML 파일 처리 차이를 찾아보시면 학습에 도움이 될 것 같아요!

2024-10-09 12:46 UTC, Indigochi1d commented on package.json
> +    ]
이 browserlist를 왜 추가해야하는지 구체적인 이유를 혹시 알고 계신가요? (이것 또한 Vite와 CRA의 차이입니다.) 10월25일 스터디 때 이 이유를 조사해오셔서 공유해주시면 좋을 것 같아요😄

2024-10-09 12:46 UTC, Indigochi1d commented on src/components/AddRestaurantModal.jsx
> +              </select>
이 때 option을 전부 나열하는 것 보다는 map함수의 적용이 더 좋아보입니다. 극단적인 예시로 만약 이 미션에서 100개의 카테고리를 요구했다면 하드코딩하기 너무 어려워져요!

2024-10-09 12:46 UTC, Indigochi1d commented on src/components/AddRestaurantModal.jsx
전체적으로 코드를 작성하실때 module.css를 채택하지 않으셨는데 이유를 듣고 싶어요! 리액트로 FE개발을 해오셨는데 그동안 css를 어떻게 적용해왔는지도 궁금합니다!

2024-10-09 12:46 UTC, Indigochi1d commented on src/components/RestaurantList.jsx
이 코드 또한 하드코딩해주셨는데요! 이런 방식은 데이터가 추가될 때 새로 많은 것을 개발자가 직접 적어야하는 불편함이 생길 것 같아요.
```javascript
const restaurants = [
    {
        category: "한식",
        icon: CategoryKorean,
        name: "피양콩할마니",
        description: "평양 출신의 할머니가 수십 년간 운영해온 비지 전문점 피양콩 할마니. 두부를 빼지 않은 되비지를 맛볼 수 있는 곳으로, ‘피양’은 평안도 사투리로 ‘평양’을 의미한다. 딸과 함께 운영하는 이곳에선 맷돌로 직접 간 콩만을 사용하며, 일체의 조미료를 넣지 않은 건강식을 선보인다. 콩비지와 피양 만두가 이곳의 대표 메뉴지만, 할머니가 옛날 방식을 고수하며 만들어내는 비지전골 또한 이 집의 역사를 느낄 수 있는 특별한 메뉴다. 반찬은 손님들이 먹고 싶은 만큼 덜어 먹을 수 있게 준비돼 있다."
    },
    {
        category: "중식",
        icon: CategoryChinese,
        name: "친친",
        description: "Since 2004 편리한 교통과 주차, 그리고 관록만큼 깊은 맛과 정성으로 정통 중식의 세계를 펼쳐갑니다."
    },
    {
        category: "일식",
        icon: CategoryJapanese,
        name: "잇쇼우",
        description: "잇쇼우는 정통 자가제면 사누끼 우동이 대표메뉴입니다. 기술은 정성을 이길 수 없다는 신념으로 모든 음식에 최선을 다하는 잇쇼우는 고객 한분 한분께 최선을 다하겠습니다."

    },
    {
        category: "양식",
        icon: CategoryWestern,
        name: "이태리키친",
        description: "늘 변화를 추구하는 이태리키친입니다."
    },
    {
        category: "아시안",
        icon: CategoryAsian,
        name: "호아빈 삼성점",
        description: "푸짐한 양에 국물이 일품인 쌀국수."

    },
    {
        category: "기타",
        icon: CategoryETC,
        name: "도스타코스 선릉점",
        description: "멕시칸 캐주얼 그릴."
    }
```

따라서 이렇게 따로 파일을 만드신 후 import/export 해와서 jsx안에서 {}문안에 쓰는 방식은 어떨까요?

2024-10-09 12:46 UTC, Indigochi1d commented on src/main.jsx
> +import App from "./App";
예은님이 사용해오신 CRA는 확장자를 명시하지 않더라고 자동으로 찾을 수 있어요! 
[링크](https://webpack.kr/configuration/resolve/#resolveextensions)를 참고하시면 도움이 될거에요!

그럼 Vite는 왜 확장자를 명시하지 않으면 안될까요? 그 이유를 적어주시면 많은 공부가 될 것 같아요! 블로그가 있다면 CRA vs Vite 라는 주제로 포스팅하는것도 아주 맛있어보입니다 ㅎㅎ..

2024-10-09 15:09 UTC, ye6194 commented on src/components/AddRestaurantModal.jsx
사실 module.css는 이번 미션을 하면서 처음 들어보는 개념인데, 제대로 찾아보지 않고 이름만 보고 '한 파일에 css를 몰아넣지 않고 여러 파일로 분할하는건가?'라는 생각을 하며 그냥 넘어갔어요...😅 그래서 제가 module.css를 사용한줄 알았답니다... 이렇게 글로 적으니 어이없기도 하고 부끄럽기도 하네요........

저는 리액트로 개발하면서 .css를 쓰지 않고 styled-components를 써요!
[style.js]
```javascript
import styled from "styled-components";

export const Container = styled.div`
  display: flex;
`;
```

[App.jsx]
```javascript
import * as S from "../styles/style"

function App() {
  return(
    <S.Container />
  )
```
또는

```javascript
import { Container } from "../styles/style"

function App() {
  return(
    <Container />
  )
```
이런식으로 쓰고있어요.

2024-10-09 15:14 UTC, ye6194 commented on src/components/RestaurantList.jsx
저는 step1의 README에
- `/templates` 에 있는 html 템플릿을 그대로 `App.jsx`에서 그릴 수 있게 해보세요. 
- `App.jsx`를 여러 개의 컴포넌트로 분리해서 그려보세요.  
  - 스타일도 별도의 css파일로 분리하여 각 컴포넌트에서 import합니다.
  
이렇게만 적혀있어서 하드코딩이나 이런건 일절 신경을 쓰지 않고 정말 templates/index.html에 있는 코드를 그대로 App.jsx 등의 파일에 옮겼어요! 실제로 `const restaurants = ...` 이 부분은 step2의 README에 있는 것이기도 하구요.
step2는 `const restaurants = ...` 이걸 쓰긴 했지만 따로 파일을 만들진 않았는데 파일로 분리하겠습니다!!

2024-10-09 15:16 UTC, ye6194 commented on src/components/AddRestaurantModal.jsx
> +              </select>
밑에 있는 코멘트와 같은 이유입니다! step1에서는 하드코딩 같은건 신경쓰지 않았어요.

> 이렇게만 적혀있어서 하드코딩이나 이런건 일절 신경을 쓰지 않고 정말 templates/index.html에 있는 코드를 그대로 App.jsx 등의 파일에 옮겼어요! 실제로 `const restaurants = ...` 이 부분은 step2의 README에 있는 것이기도 하구요. step2는 `const restaurants = ...` 이걸 쓰긴 했지만 따로 파일을 만들진 않았는데 파일로 분리하겠습니다!!

2024-10-09 15:16 UTC, ye6194 commented on .eslintrc.cjs
> +  env: { browser: true, es2020: true, node: true },
한번 찾아보겠습니다!

2024-10-09 15:17 UTC, ye6194 commented on package.json
> +    ]
헉 저건 그냥 지피티한테 물어봤더니 저렇게 하라고 해서 한건데 자세한 이유를 알아보도록 하겠습니다...!

2024-10-09 15:18 UTC, ye6194 commented on src/main.jsx
> +import App from "./App";
저도 이쯤되니 CRA vs Vite가 너무 궁금하네요ㅎㅎ...

2024-10-09 15:19 UTC, Indigochi1d commented on src/components/AddRestaurantModal.jsx
역시 styled-components를 쓰고 계시군요!

2024-10-09 15:22 UTC, Indigochi1d commented on src/main.jsx
> +import App from "./App";
step3부터는 CRA로 환경설정 해놓으신 것을 다시 Vite로 하는 것은 어떠신가요? 환경설정을 바꾸는 과정에서 더 이해를 잘할 수 있는 부분이 생길 것 같아요

2024-10-09 15:40 UTC, ye6194 commented
저는 리액트 개발 서버를 열 때 항상 npm start만 했어서 이번에도 그렇게 했는데 안되더라구요.
npm start를 했더니
npm error Missing script: "start"라는 에러
'react-scripts'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다.라는 에러
public 안에 index.html이 없다는 에러
index.js가 src 안에 없다는 에러

eslint가 html파일의 `<` 이 문자에서 parsing error를 일으키기도 하고
.eslintrc.cjs의 `module.exports` 이 부분에서 'module' is not defined 이런 에러
등등 온갖 에러가 떴었어요...😭😭😭

그래서 npm install ~ 하면서 필요한 패키지를 설치하고 .eslintrc.cjs 고치고 어쩌고 하면서 나름 해결했긴 했네요...
솔직히 이건 원인은 안 알아보고 지피티에게 모두 물어봐서 해결했습니다.

Vite와 CRA는 처음 들어보는데 이것들 때문에 고생했을 줄은... 그게 뭔지 알아보면서 꼭 저를 고생하게 한 원인을 찾아보겠습니다.

2024-10-09 15:45 UTC, ye6194 commented on src/components/AddRestaurantModal.jsx
styled-components가 메이저한 라이브러리인가 보네요😮

2024-10-11 11:59 UTC, wzrabbit requested changes
@ye6194 👋🏻 

안녕하세요, 예은님! 저는 그리디의 외부 리뷰어를 맡은 김의천이라고 해요. 초록 스터디에서는 제 계정명이 닉네임이어서 당황하셨을 수도 있을 것 같아보이는군요 🍿 저는 외부에서는 주로 요술토끼라는 닉네임을 사용해요.

한창 React를 다루시다가 컴포넌트를 다뤄보는 미션으로 돌아오신 소감은 어떠실지 궁금하네요. 어쨌든, 리뷰 시작해 볼게요!

## 1️⃣ 리뷰
코드는 전체적으로 구성이 잘 되어 있었던 것 같아요! 미션에 명시된 탬플릿을 명시된 대로 잘 나눠서 구현해 주신 것 같아요. 이후 미션 진행 단계에 따라 자주 사용될 만한 컴포넌트들은 더 나눌 수도 있어보이는데, 그 때도 필요에 따라 잘 나눠주시면 좋을 것 같습니다!

css 파일들 또한 일관성을 잘 갖추시면서 나눠주신 것 같습니다. 컴포넌트명과 대응되는 css 파일들을 `/style` 디렉토리에 별도로 만들어주셨는데 컴포넌트에 대응되는 스타일시트 파일을 찾기 쉬웠던 것 같아요. 나중에는 프로젝트의 규모가 커지고 여러 파일들이 모여 하나의 컴포넌트를 이루는 방식을 이룰 수도 있을텐데, 이 경우에는 아래의 방식도 추천드리고자 해요. 필요에 맞게 원하시는 방법을 가져가 보시면 좋겠습니다 👍🏻 결론적으로 지금의 구조는 상당히 좋아보여요

```
.
└── src/
    └── components/
        └── MyComponent/
            ├── MyComponent.jsx
            ├── MyComponent.css
            └── other files...
```

구조의 경우에도, 간단한 구조가 생기더라도 기능이 잘 분배되어 있고, 개발하는 데 있어서 불편함을 느끼시지 않는다면 문제되지는 않는다고 생각해요. 오히려 간단한 프로젝트를 너무 복잡한 구조로 나누려 한다면 그거대로 힘들지 않을까 생각해요.

그 외에도, 예은님의 성장을 위해 자잘한 코멘트들을 달아보았으니, 고민해 보시면 좋을 것 같아요!

## 2️⃣  개발환경
미션 중 개발환경 설정에 많은 노력을 쏟아부으셨군요, 우선 정말 수고하셨습니다 💪🏻 

저도 예은님이 올려주신 질문을 보고 미션 저장소의 파일 구조를 다시 살펴보았는데요, 미션 진행 전의 커밋인 d92efec 를 기준으로 **이미 Vite로 개발환경 세팅이 되어 있는 상황**이었던 것으로 보여요. 즉, 별도의 추가 개발환경 설정 없이 바로 미션에서 요구하는 요구사항들인 **컴포넌트를 이해하고, 하나의 UI를 여러 개의 컴포넌트로 분리해보는 것** 에 집중할 수 있도록 기획된 것으로 보입니다. 

아래는 미션 초기인 상황에서 개발서버를 켠 모습이에요. 이미 개발환경 설정은 되어 있죠?

<img src="https://github.com/user-attachments/assets/08f8856d-bcb3-419f-931a-f355ae350e07" width="300px" />

* 리뷰 중 Vite와 CRA라는 용어가 오갔는데, 지금은 이것들을 둘 다 **React 개발 환경을 간편하게 구성하고 빠르게 프로젝트를 생성할 수 있는 도구** 정도라고 생각해주셔도 충분할 것 같습니다.

이후 예은님께서 커밋해주신 fe6716b 커밋을 기준으로는
- `react-scripts` 패키지를 설치해주셨고
- 터미널에서 `npm run start` 으로 `react-scripts`를 이용해 개발 서버를 실행할 수 있도록 설정

해 주신 것으로 보이는데, `react-scripts`는 CRA에서 사용하는 라이브러리이고, Vite로 구성된 프로젝트에서는 이미 `npm run dev` 를 터미널에 입력하는 것으로 개발 서버를 실행할 수 있으므로 불필요한 설정일 확률이 높습니다. 의도하신 것이 아니라면 제거해주실 것을 제안드려요.

1. `npm uninstall react-scripts` 를 터미널에 입력해 `react-scripts`를 제거합니다.
2. `package.json` 의 `scripts` 에서, `"start": "react-scripts start"` 를 제거합니다.

이외에 예은님께서 메인테이너님과의 상호 리뷰를 하신 이후 해 주신 질문 중 일부에 대해서도 답변해 보고자 해요.

> 저는 리액트 개발 서버를 열 때 항상 npm start만 했어서 이번에도 그렇게 했는데 안되더라구요.

Vite로 생성된 프로젝트라면 일반적인 현상입니다. `npm run start`가 아니라 `npm run dev`를 이용해 개발서버를 실행하셔야 합니다. `npm run start`로 지금까지 React 프로젝트를 실행하셨다면, 그건 CRA로 프로젝트를 생성하셨거나 다른 방법을 사용하셨을 가능성이 높을 것 같습니다.
- `npx create-react-app` 과 비슷한 명령어를 사용해 React 프로젝트를 생성하셨다면, 그건 CRA를 이용한 방법입니다.

> npm error Missing script: "start"라는 에러
'react-scripts'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다.라는 에러
public 안에 index.html이 없다는 에러
index.js가 src 안에 없다는 에러

넷 모두 CRA로 프로젝트를 구성하고 `react-scripts`를 이용해 개발 서버를 열었을 경우 발생하는 문제들입니다.

- 1, 2번 문제의 경우 위의 질문과 동일한 이유입니다.
- 3, 4번 문제의 경우 CRA로 생성된 프로젝트라면 `public/` 디렉토리 안에 `index.html` 이 위치해야 하고, 프로젝트의 진입점인 `index.js`가 `src/` 디렉토리 안에 위치해야 합니다. 본 프로젝트는 Vite로 구성된 프로젝트이므로 `index.html`과 `index.js` 가 다른 디렉토리에 위치하는 상황이며, 본래 세팅된 Vite를 이용해 프로젝트를 실행하는 경우에는 문제가 생기지 않을 것입니다.

eslint 관련 에러의 경우에는 저도 클론해와서 확인해봤는데, 별다른 에러를 찾지 못했어요. 혹시 에러가 나는 상황을 재현해주실 수 있다면 재현 방법을 알려주시면 감사하겠습니다.

저는 여기까지! 2단계 리뷰도 머지않아 드릴 예정입니다. 만약 반영을 하신다면 2단계에서 반영해주세요~

2024-10-11 11:59 UTC, wzrabbit commented on src/components/AddRestaurantModal.jsx
> +    <>
1. `<>...</>` 는 무엇을 의미할까요? 무슨 역할을 할까요?
2. 작성해 주신 코드를 둘러봤을 때, `<>...</>` 를 생략할 수 있는 경우가 보이는 것 같아요. 어떤 경우에 생략할 수 있고, 어떤 경우에는 필수적으로 사용해야 할 지를, JSX의 규칙, 그리고 `<>...</>` 가 하는 역할과 연관지어서 설명해 주실 수 있나요?

Docs: https://react.dev/learn/writing-markup-with-jsx

2024-10-11 11:59 UTC, wzrabbit commented on src/components/AddRestaurantModal.jsx
본 단계에서는 선택사항이기는 하지만, 이미 React를 사용하다가 오셨으니 CSS Module에 대해서 접해보시는 것도 좋을 것 같아 보여요. 엄연히 이번 단계에서도 다루기 괜찮은 주제가 될 수 있을 것 같습니다 💪🏻 

컴포넌트는 외부에 의존하지 않고 독립적으로 로직을 짜고, 재사용에 용이하도록 설계할 수 있는 코드 조각이라고 생각해요. 그런데 css 특성상, 여러 스타일시트가 같이 사용될 경우 충돌하는 id 및 class가 생길 수도 있을 거에요. 컴포넌트를 재사용하려는 입장에서 이렇게 충돌 가능성을 생각해 컴포넌트의 내부 구조를 다 봐야 하고, 이에 맞춰서 충돌하지 않도록 코드를 짜고자 한다면 간단한 로직을 추가하는 것조차 어려워지니, 궁극적으로 **위험하고, 사용하기 힘든** 컴포넌트가 될 수 있을 것이라고 생각해요.

1. CSS Module은 어떻게 하면 사용할 수 있는지
2. CSS Module을 사용할 경우 그냥 css를 사용했을 때와 비교했을 때, 어떠한 이점을 누릴 수 있을 지

이 두 가지에 대해 고민해 보시면 좋을 것이라고 생각해요.

2024-10-11 11:59 UTC, wzrabbit commented on src/components/Header.jsx
> +          <img src="./add-button.png" alt="음식점 추가" />
```html
<img src="./add-button.png" alt="음식점 추가">
```
위와 같이 사용하는 것은 안 되는 것일까요? HTML에서의 `<img>` 태그는, 실제로는 닫지 않아도 문제 없이 작동하고, 유효한 문법입니다. React에서는요?

2024-10-14 10:51 UTC, ye6194 commented on src/components/AddRestaurantModal.jsx
> +    <>
앗 이 경우에는 생략해도 되는데 실수로 지우지 않았네요.
'리액트는 엘리먼트를 하나의 태그로 감싸 반환해야한다'라고만 알고 자세한 이유는 찾아보지 않았었는데 의천님이 첨부해주신 링크를 보고 이번 기회에 자세하게 알고 갑니다.😊

링크를 보고 학습한대로 답변해보자면,
1. `<>...</>`는 Fragment라고 하는데, 다른 태그와 달리 브라우저 상에서 html 트리 구조에서 흔적을 남기지 않고도 그룹으로 묶을 수 있게 해줍니다.
2. jsx는 자바스크립트 객체로 변환되는데, 하나의 배열로 감싸지 않은 하나의 함수에서는 여러 객체를 반환할 수 없습니다. 따라서 한 태그로 묶어 하나의 루트 엘리먼트로 반환해야 합니다. 이때 fragment를 써도 되고, `<div>` 등의 다른 태그로 감싸도 됩니다.
AddRestaurantModal.jsx에서는 이미 `<div>`로 감쌌기 때문에 이 경우에 fragment는 생략해도 됩니다.

2024-10-14 11:03 UTC, ye6194 commented on src/components/Header.jsx
> +          <img src="./add-button.png" alt="음식점 추가" />
한 번도 생각해보지 않았던 주제네요😮

위 링크(Docs: https://react.dev/learn/writing-markup-with-jsx)를 보니까 그냥 jsx는 명시적으로 태그를 닫아야 한다고만 나와있어서 따로 찾아봤는데 jsx는 자바스크립트와 xml을 혼합한 문법을 사용하기 때문이군요!
html은 <img> 같은 태그는 자동으로 닫힌 걸로 인식하는 반면, xml에서는 모든 태그가 열림과 닫힘이 있어야 하므로 <img> 같은 태그도 명시적으로 닫아줘야 한다고 하네요.

2024-10-14 11:51 UTC, ye6194 commented
안녕하세요 의천님🙌

우선 답변이 늦어져서 죄송합니다😭😭 시험기간이라 정신이 없었네요...
의천님 코멘트를 보고 답변을 달면서 리액트에 대해 조금이나마 더 알게 되었습니다. 저는 리액트를 쓰고 있긴 하지만 뭔가 자세하게 알지는 못하고 수박 겉핥기 느낌으로 알고 있다는 것을 다시한번 느끼기도 했어요. 뭔가 알고 있긴 하지만 잘 모르는...? 중간중간 뚫려있는 젠가처럼 위태로운 상태같네요ㅎㅎ

<br/>

> 1. npm uninstall react-scripts 를 터미널에 입력해 react-scripts를 제거합니다.
> 2. package.json 의 scripts 에서, "start": "react-scripts start" 를 제거합니다.

이건 의천님 말씀대로 2단계에서 반영하겠습니다!

그리고 eslint 에러는 왜 나는지 어떻게 재현하는지를 저도 모르겠네요ㅠ 다른 프로젝트를 할 때 다른 분은 오류가 안 나는데 저만 났던 것 같기도 합니다.
![image](https://github.com/user-attachments/assets/6a170cda-0a15-4e46-92df-f21202a0fc9a)
이건 퍼온 사진인데 이런 에러가 떠요. 인터넷에 나와있는대로 다 해봤는데 안 없어지고 결국 eslint 검사에서 html을 빼야 없어지더라구요.

2024-10-17 11:25 UTC, wzrabbit approved these changes
미션 뿐만 아니라 제가 드렸던 코멘트를 기반으로 더 학습하시느라 수고 많이 하셨습니다. 질문에 대한 답변뿐만 아니라 "왜 그런지" 에 대해 직접 알아보신 것 같아서 좋네요 👍🏻 

2단계 미션에도 코멘트를 드렸으니 확인해 주시길 바래요!

2024-10-17 11:25 UTC, wzrabbit commented on src/components/AddRestaurantModal.jsx
> +    <>
열심히 학습하신 것 같네요 😄 추가로 `<React.Fragment>...</React.Fragment>`로도 쓰는 방법이 있는데, 추후 이 부분도 알아보시면 좋을 것 같아요! 과연 `<>...</>` 와는 무슨 차이가 있을까요?

2024-10-20 18:42 UTC, ye6194 commented on src/main.jsx
> +import App from "./App";
앗 지금 확인했네요...!! step2에서 바꾸게 되었는데 범수님 말대로 CRA와 Vite에 대해 더 알게 되어서 좋았습니다! 😊

2024-10-20 18:45 UTC, ye6194 commented on src/components/AddRestaurantModal.jsx
> +    <>
`<React.Fragment>...</React.Fragment>`는 `<>...</>`와 다르게 key 속성을 사용할 수 있네요!
밑은 제가 찾아본 예제입니다😮

```js
function Glossary(props) {
  return (
    <dl>
      {props.items.map(item => (
        // React는 `key`가 없으면 key warning을 발생합니다.
        <React.Fragment key={item.id}>
          <dt>{item.term}</dt>
          <dd>{item.description}</dd>
        </React.Fragment>
      ))}
    </dl>
  );
}
```

2024-10-20 18:50 UTC, ye6194 commented on src/main.jsx
> +import App from "./App";
찾아본 결과 웹팩 기반은 CRA는 확장자를 명시하지 않아도 자동으로 처리하지만, ESM 기반인 Vite는 ES Modules 표준을 따르기 때문에 파일 확장자를 명시해야 한다는 것을 알게 되었어요.

2024-10-23 11:34 UTC, merged