[2단계
cho-log/self-paced-react pull request #21
Opened 2024-10-08 07:00 UTC by Songhyejeong

2024-10-08 16:02 UTC, gogo1414 reviewed
안녕하세요, 혜정님😊
리뷰어 김준수입니다!

2단계 미션은 1단계에서 어느정도 구현을 했으면, 간단하게 진행되었던거 같아요!!

코드 리뷰의 내용은 1단계와 유사하게 공백의 유무와 코드 사용에 대한 궁금점을 위주로 달아봤어요! 작성할 내용을 1단계에서 다 한 느낌이라 2단계 미션 코드 리뷰는 상대적으로 짧네요..!

이번 주차 고생하셨습니다!!😊😊😊

2024-10-08 16:02 UTC, gogo1414 commented on src/App.jsx
> +  let filteredRestaurants = [];
필터링된 레스토랑이 계속 변경되는 값이라고 생각하셔서 `let` 으로 선언하신 걸까요??

2024-10-08 16:02 UTC, gogo1414 commented on src/App.jsx
> +        filteredRestaurants.push(item);
그냥 넣는 방식도 있는데 `push`를 사용하신 이유가 궁금해요!!

2024-10-08 16:02 UTC, gogo1414 commented on src/components/aside/AddRestaurantModal.jsx
> +const AddRestaurantModal = () => {
```suggestion
import { CATEGORYOPTION } from '../constants/CategoryOption';

const AddRestaurantModal = () => {
```
줄바꿈이 없어요!!

2024-10-08 16:02 UTC, gogo1414 commented on src/components/main/restaurant/RestaurantCard.jsx
> +  }
`switch` 방식으로 구현하셨네요! 해당 부분은 따로 분리해서 함수화가 가능하지 않을까요??

2024-10-08 16:02 UTC, gogo1414 commented on src/components/main/restaurant/RestaurantList.jsx
> +const RestaurantList = ({ restaurants }) => {
```suggestion
import RestaurantCard from './RestaurantCard';

const RestaurantList = ({ restaurants }) => {
```
공백이 없어요!!

2024-10-08 16:02 UTC, gogo1414 commented on src/components/main/restaurant/RestaurantList.jsx
> +export default RestaurantList;
```suggestion
};

export default RestaurantList;
```
여기도 공백이 없어요!!

2024-10-08 16:02 UTC, gogo1414 commented on src/components/main/restaurant/RestaurantList.jsx
> +              />
`RestaurantCard`를 따로 분리해서 사용하는 방법 되게 좋은거 같아요👍

2024-10-10 02:42 UTC, Songhyejeong commented on src/App.jsx
> +  let filteredRestaurants = [];
네 변경되는 값이라고 생각해서 `let`으로 선언했습니다..!

2024-10-10 02:45 UTC, Songhyejeong commented on src/App.jsx
> +        filteredRestaurants.push(item);
[4.2](https://github.com/parksb/javascript-style-guide?tab=readme-ov-file#arrays--push) 코드 컨벤션 보다가, 배열에 직접 값을 할당하는 것 보다 push를 사용하는 것이 좋다고 하여 `push`를 사용했는데 정확한 장점은 모르겠습니다,, 
더 찾아봐야할 거 같네요!

2024-10-10 02:46 UTC, Songhyejeong commented on src/components/main/restaurant/RestaurantCard.jsx
> +  }
네 ! 이 부분은 함수화하여 관리하는 것이 좋을 거 같네요 👍

2024-10-10 04:15 UTC, gogo1414 commented on src/App.jsx
> +        filteredRestaurants.push(item);
컨벤션을 따르고 계셨군요..!! 멋지십니다👍
제 생각을 얘기 드리자면 레스토랑 가게가 추가될 경우 직접 값을 할당하는 방식이 어려워지니 혜정님처럼 구현하는 방향이 올바른거 같아요!😊

2024-10-10 04:17 UTC, gogo1414 commented on src/App.jsx
> +  let filteredRestaurants = [];
필터 레스토랑의 내부의 값이 삭제, 추가되는 방식이니 `const`도 괜찮다고 생각이 들어서 여쭤봤어요😊

2024-10-10 05:06 UTC, Songhyejeong commented on src/App.jsx
> +  let filteredRestaurants = [];
저도 준수님 의견 듣고 `const` 괜찮을 거 같아서 적용해봤는데,, 
오류가 떠서 이부분은 다시 공부해보겠습니다..!

2024-10-10 05:52 UTC, gogo1414 commented on src/App.jsx
> +  let filteredRestaurants = [];
좋습니다👍

2024-10-10 15:45 UTC, Indigochi1d requested changes
안녕하세요 혜정님! 3주차 미션 step2까지 리뷰를 완료했습니다! 평소 리액트를 사용해오셨어서 그런지 역시 코드가 깔끔했어요. 특히 컨벤션을 꼼꼼히 지켜주신 모습은 정말 보기 좋았습니다! 

step1에서 리뷰거리를 많이 소모하고 사실 step2에서 요구하는 구현이 많이 적다보니 리뷰할 거리가 많이 없어서 조금 아쉽기도 하네요🫤 이번주 미션도 수고하셨고 중간고사 끝나고 스터디에서 이번 미션에 대해서 많이 공유해보아요! 수고하셨습니다!

2024-10-10 15:45 UTC, Indigochi1d commented on docs/file_structure.png
👍🏻

2024-10-10 15:45 UTC, Indigochi1d commented on src/App.jsx
> +  let filteredRestaurants = [];
결론만 말씀드리면 `const`는 쓸 수 없습니다! 왜냐하면 아래의 코드에서 배열 전체를 재할당하는 시도를 하기 때문이에요.
```javascript
if (category === '전체') {
    filteredRestaurants = restaurants;
  } 
```

2024-10-10 15:45 UTC, Indigochi1d commented on src/App.jsx
> +        filteredRestaurants.push(item);
컨벤션대로 push를 통해 배열에 직접 값을 할당하는 방식을 피한것 너무 잘하신 것 같아요 👍🏻  컨벤션을 정말 꼼꼼히 읽어보신 듯 합니다..! 저는 이 부분을 filter함수를 써서 구현했던 기억이 있어요. 혜정님의 방식대로 하는것과 제가 했던 방식의 비교를 해보겠습니다.

```javascript
if(category !== "전체"){
    filteredRestaurants = restaurants.filter(restaurant => restaurant.category === category);
}
```

## filter vs map 
#### filter
`filter`는 조건에 맞는 요소만 반환하는 메서드에요. 즉, 카테고리가 선택되었을 때 조건에 맞는 요소만 반환할 수 있죠! 또 [filter 메서드의 docs](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)를 보게 되면 주어진 배열의 일부에 대한 얕은 복사본을 반환값으로 가집니다. 즉, 제공된 함수에 의해 구현된 테스트를 통과한 요소로만 "필터링"하게 되죠. 
#### map
반면 `map`은 배열의 각 요소에 대해 실행한 `callback`의 결과를 모은 새로운 배열을 반환합니다. 이 때 코드를 다시 보면 반환된 배열은 사용되지 않고 filteredRestaurants에 조건이 맞는 요소만 push되고 있어요. 즉, 필터링을 map+array.push  로 구현해주셨지만 사실 filter 함수로도 충분히 가능한 작업이라고 생각해요.

가독성 측면에서도 `filter`가 의도파악에 조금 더 도움이 될 것 같긴 하는데 혜정님은 어떻게 생각하시나요? 성능면에서도 `filter`는 불필요한 배열을 만들지 않으니 더 낫다고 생각하는데 사실 지금 상황에서는 성능면에서 차이가 없을 것 같지만요!

2024-10-10 15:45 UTC, Indigochi1d commented on src/components/aside/RestaurantDetailModal.jsx
> +        <h2 className={`${styles.modalTitle} text-title`}>음식점 이름</h2>
이 코드를 보면 Modal.module.css를 styles로 import 해와서 사용한 모습인데요! text-title은 아마 저 css파일안에 있지 않을거에요. 그렇다면 text-title이 왜 사용가능한지 혹시 이유를 아시나요?

2024-10-10 15:45 UTC, Indigochi1d commented on src/components/constants/CategoryOption.jsx
👍🏻

2024-10-10 15:45 UTC, Indigochi1d commented on src/components/constants/Restaurants.jsx
이렇게 나눠서 작성하신것 좋습니다!!
한가지 궁금한점은 CATEGROYOPTION은 대문자로, restaurants는 소문자로 작성하셨는데 그 이유를 들어볼 수 있을까요?

2024-10-10 15:45 UTC, Indigochi1d commented on src/components/main/restaurant/RestaurantCard.jsx
> +};
switch문을 통한 함수.. 💯 한눈에 보기에 너무 읽기 쉬운 코드네요!

2024-10-10 15:45 UTC, Indigochi1d commented on src/components/main/restaurant/RestaurantCard.jsx
> +  const image = getCategoryIcon(alt);
alt로 카테고리 아이콘을 찾아 넣으셨군요 ⭕

2024-10-10 15:45 UTC, Indigochi1d commented on src/components/main/restaurant/RestaurantList.jsx
> +        {restaurants.length > 0 &&
이 코드는 어떻게 작동하나요?

2024-10-11 13:42 UTC, Songhyejeong commented on src/components/constants/Restaurants.jsx
CATEGORYOPTION은 확실히 상수라고 생각했는데, restaurants은 상수라고 하기에 나중에 추가하거나 삭제할 수도 있을 것이라 생각해서 애매 하다고 생각 해서 소문자로 작성했습니다..! 
하나만 대문자로 작성하니, 보기에 헷갈릴 수도 있겠네요 
둘 다 대문자로 바꾸는 것이 좋을 거 같네요 !

2024-10-11 13:43 UTC, Songhyejeong commented on src/components/main/restaurant/RestaurantCard.jsx
> +};
감사합니다..!

2024-10-11 13:45 UTC, Songhyejeong commented on src/components/main/restaurant/RestaurantList.jsx
> +        {restaurants.length > 0 &&
restaurants이 제대로 불러와지기 이전에, map 함수가 작동 되는 것을 방지하려고 추가한 코드입니다!

2024-10-11 13:49 UTC, Songhyejeong commented on src/App.jsx
> +        filteredRestaurants.push(item);
map 함수와 조건을 주어 필터링 하는 것 보다, 확실 filter를 사용하는 것이 의도를 파악 하기에도 쉽고 
간결하게 작성할 수 있을 것 같아 이 부분에는 filter를 사용하는 것이 맞는 방향인 것 같아요! 
성능 측면에서도 filter가 좋다는 것을 처음 알았는데 filter를 사용하기 적합할 경우에 자주 사용하는 습관을 들여야겠네요 ! 👍

2024-10-11 13:52 UTC, Songhyejeong commented on src/components/aside/RestaurantDetailModal.jsx
> +        <h2 className={`${styles.modalTitle} text-title`}>음식점 이름</h2>
text-title이 지금 App.css에서 전역으로 관리 되고 있어서 그런 것 같아요! 

궁금한 점이 있는데, 그렇다면 전역 CSS가 자식에게 모두 적용될 수 있는 이유가 어떤 이유인지 궁금합니다,,!

2024-10-13 23:42 UTC, Indigochi1d commented on src/components/aside/RestaurantDetailModal.jsx
> +        <h2 className={`${styles.modalTitle} text-title`}>음식점 이름</h2>
CSS상속과 캐스케이딩에 대해서 찾아보시면 될 것 같아요!
[링크](https://poiemaweb.com/css3-inheritance-cascading)로 남겨놓을게요

2024-10-13 23:43 UTC, Indigochi1d reviewed
수고하셨습니다!

2024-10-14 03:03 UTC, merged