[3단계 미션] 송혜정 3단계 미션 제출합니다.
cho-log/self-paced-react pull request #29
Opened 2024-11-05 09:24 UTC by Songhyejeong

안녕하세요 리뷰어님! 잘부탁드립니다. 오랜만에 다시 점심 뭐먹지 구현 이어가니까 재밌었습니다. 참고 문서를 먼저 읽어보고 시작하니 소요되는 시간을 줄일 수 있었던 것 같습니다!

## 신경쓴 점
이번 미션에서는 데이터의 흐름을 파악하는 것에 신경을 쓰면서 구현하였습니다. 
함수 전달과 호출, 화살표 함수 사용과 그냥 전달하는 방법이 헷갈려서
`onClick={() => onCardClick({ name, description })}` 여기서 `onClick={onCardClick({ name, description })}` 이 코드는 왜 실행이 안되는지 이해하는 것이 어려웠던거 같습니다..!
평소에 대충 넘어가던 부분을 찾아보고 이해하니 좋았던 것 같습니다!

## 구현 기능
1.  아이템을 클릭하면 정해진 텍스트를 그대로 보여주는 모달을 열고 닫습니다.
3.  클릭한 아이템의 정보를 모달에 내려줄 수 있도록 개선합니다.

### 키워드
- event handler (feat. side effect)
- conditional rendering
- lifting state up

### 파일 구조, props 흐름

<img width="789" alt="Screenshot 2024-11-05 at 5 24 43 PM" src="https://github.com/user-attachments/assets/5530d8ef-349a-409e-8142-5dbd8be54e23">

### 실행 영상

https://github.com/user-attachments/assets/6cd42140-871b-4274-8412-2a6055659849

2024-11-06 03:32 UTC, ye6194 commented
안녕하세요 혜정님! 코드 잘 읽었습니다. 

components 폴더를 깔끔하게 잘 정리해놓으신 것 같아요.
그리고 저도 이번 미션을 할 때 혜정님과 마찬가지로 `onClick={함수이름()}` 이렇게 했다가 제대로 작동이 안돼서 `onClick={() => 함수이름()}` 이렇게 고친 경험이 있습니다. 예전에도 리액트를 하면서 분명히 다뤄본 적이 있을텐데 그때마다 대충 gpt를 써서 넘아가느라 제대로 몰랐던 것 같아요. 이번 기회에 저도 혜정님처럼 이유를 알게 되어 좋았습니다!

미션 하시느라 수고 많으셨습니다!

2024-11-06 04:05 UTC, ye6194 commented on src/App.jsx
> +
저는 hanleCardClick 함수를 RestaurantList에, handleCloseButtonClick 함수를 RestaurantDetailModal에 두었는데 혜정님은 App에 두셨네요.

2024-11-06 04:05 UTC, ye6194 commented on src/App.jsx
> +  const hanleCardClick = ({ name, description }) => {
여기서 구조 분해 할당을 잘 이용하신 것 같아요😮 이렇게도 할 수 있군요

2024-11-06 04:05 UTC, ye6194 commented on src/App.jsx
>  import { restaurants } from './components/constants/Restaurants';
6, 7번째 줄과 중복되어서 빼는게 좋을 것 같아요.

2024-11-06 04:05 UTC, ye6194 commented on src/App.jsx
> +            onCloseButtonClick={handleCloseButtonClick}
handleCloseButtonClick을 지우고 onCloseButtonClick={() => setIsModalOpen(false)} 이렇게 해도 작동이 되더라구요. 각 방법마다 장단점이 있을 것 같은데 혜정님은 어떤 방법이, 왜 더 좋으신지 궁금합니다!

2024-11-06 04:05 UTC, ye6194 commented on src/App.jsx
>        </aside>
저는 이 부분에서 prop이 더 많아서 코드가 좀 더 긴데 혜정님은 필요한 prop만 딱 넣어두셔서 코드가 더 깔끔한 것 같아요.

2024-11-07 00:27 UTC, Songhyejeong commented on src/App.jsx
>  import { restaurants } from './components/constants/Restaurants';
헉 그러네요 !

2024-11-07 21:07 UTC, Indigochi1d requested changes
**안녕하세요 혜정님! step3리뷰를 마쳤습니다!** 
오랜만의 미션에 조금 어색하면서 한달전에 했던게 기억이 안 나기도 하고 그랬을 것 같아요! 이번 미션에서는 굉장히 간단하지만 `props로 setter함수를 보내 컴포넌트 간 상태 단방향 데이터 흐름을 지키고 props로 받은 상태를 조건부 렌더링할 수 있어?` 를 물어보는 미션이었던 것 같습니다! 이러한 흐름을 이미 알고 계셨던 혜정님에게는 매우 쉬운 미션이었을거라고 생각해요.😄

### onClick 에서의 함수전달과 호출
 
> 이번 미션에서는 데이터의 흐름을 파악하는 것에 신경을 쓰면서 구현하였습니다.
> 함수 전달과 호출, 화살표 함수 사용과 그냥 전달하는 방법이 헷갈려서
> onClick={() => onCardClick({ name, description })} 여기서 onClick={onCardClick({ name, description })} 이 코드는 왜 실행이 안되는지 이해하는 것이 어려웠던거 같습니다..!
> 평소에 대충 넘어가던 부분을 찾아보고 이해하니 좋았던 것 같습니다!

헤정님이 찾아보시고 이해한 결과를 스터디에서 공유하는 시간을 가지면 좋을 것 같습니다!
제가 아는 바로는 렌더링 될 때` 함수를 즉시 호출하느냐 또는 지연하여 호출할 준비만 하느냐의 차이`라고만 알고 있습니다. 정확한 React 프로세스의 렌더링 동작과  JSX내부에서 평가하는 방식은 정확히 모르겠네요😢 찾아보고 알게되면 포럼에 올릴게요! 실행컨텍스트와도 연관이 있어보이는데 말이죠🤔

2024-11-07 21:07 UTC, Indigochi1d commented on src/App.jsx
> +  const [selectDescription, setSelectDescription] = useState('');
Modal에 관한 State를 각각 선언해주셨네요! 현재 Name과 Description이 레스토랑 정보에 있는 것이기에 상태로 선언해서 모달에 정보를 전달할 때 쓰고 있어요.
그런데 만약 Modal에 구현해야 할 것이 많아져서 Name과 Description만이 아닌 전달해야하는 속성이 6개정도 된다고 생각해보면...(하필 6개인거는 제 맘입니다ㅎ) 그때마다 모든 상태를 선언하는 것은 코드 가독성과 유지보수에 있어서 불필요하다고 생각해요. 혜정님의 생각은 어떠신가요?
저는 그래서 이런 방법으로 코드를 만들었던 기억이 있습니다.
```javascript
const [isModal, setIsModal] = useState({
        isOpen: false,
        restaurants:{
            name:"",
            description:"",
        }
    });
```
이렇게 하면 모달에 관한 정보를 한꺼번에 관리할 수 있고 props로 여러개를 전달하지 않아도 되어서 매우 편했던 경험이 있어요! 혜정님의 의견이 궁금합니다🤔

2024-11-07 21:07 UTC, Indigochi1d commented on src/App.jsx
> +  const hanleCardClick = ({ name, description }) => {
별건 아니지만 오타 난거 같아요! `handleCardClick` 이 되어야할 것 같네요😄

2024-11-07 21:07 UTC, Indigochi1d commented on src/App.jsx
>          <CategoryFilter category={category} onChangeCategory={setCategory} />
setter함수를 하위 컴포넌트로 전달하실때 `on~`으로 네이밍 해주셨네요! 리액트 공식문서에도 그렇게 나와있긴 합니다만 여태껏 저는 setter함수 이름 그대로 props로 넘겨왔어요..!
타인이 제 코드를 볼 때 

> 이건 상위 컴포넌트에서 상태를 정하러온 setter함수임.

라는 걸 나타내고 싶어서 그렇게 해왔었는데 혹시 이런 setter함수나 함수의 네이밍 컨벤션에 관해서 알고 적용하신거라면 알려주세요!

2024-11-07 21:07 UTC, Indigochi1d commented on src/App.jsx
> +          onCardClick={hanleCardClick}
여기도요! `handleCardClick`!!

2024-11-07 21:07 UTC, Indigochi1d commented on src/App.jsx
> +        )}
요구사항대로 구현을 잘해주셨네요!! 👍🏻

2024-11-07 21:07 UTC, Indigochi1d commented on src/components/aside/RestaurantDetailModal.jsx
> +      <div className={styles.modalBackdrop} onClick={onCloseButtonClick}></div>
꼼꼼히 구현을 잘 해주셨네요👍🏻

2024-11-10 08:12 UTC, merged