[4단계 미션] 송혜정 미션 제출합니다.
cho-log/self-paced-react pull request #31
Opened 2024-11-05 13:42 UTC by Songhyejeong

안녕하세요 리뷰어님! 
4단계 미션도 수고 많으셨습니다! 이번 주차는 특히 리액트에 대해서 조금씩 깊게 알아가는 것 같아서 좋았습니다..!

### 궁금한점
구현 하다 보니까 `AddRestaurantModal` 컴포넌트랑, `App` 컴포넌트에 함수도 많고 상태도 많아서 책임이 많아 보이는 것 같네요.. 평소 궁금했던 것 중에 구현을 하다가 책임이 많아지는 것 같을 때 리팩터링을 진행했었는데 이 경우 수정이 조금 복잡해지더라구요
리뷰어님은 처음에 파일 구조와 컴포넌트를 구상할 때 어떤 기준으로 짜시는지 궁금합니다..!

### 구현 기능
- 레스토랑 추가 모달 구현
- 레스토랑 폼을 입력하고 추가하는 기능 구현
- 입력 안한 폼이 있을 시 경고 출력
- 재사용할 수 있는 Modal 컴포넌트 만들기

### 키워드
- controlled vs uncontrolled
- children props

### 파일 구조, props 흐름
<img width="659" alt="Screenshot 2024-11-05 at 8 47 39 PM" src="https://github.com/user-attachments/assets/87d2be33-f51d-4ace-8119-8732f7809e87">

## 실행 영상

https://github.com/user-attachments/assets/1aec6846-79c8-4cbd-a575-95d18e16f53a

2024-11-06 07:54 UTC, ye6194 commented on src/App.jsx
>    }
if-else if문이 아닌 if문 두개를 쓰신 특별한 이유가 있나요??

2024-11-06 07:54 UTC, ye6194 commented on src/App.jsx
>  import { restaurants } from './components/constants/Restaurants';
step3과 마찬가지로 지우는게 좋을 것 같습니다!

2024-11-06 07:54 UTC, ye6194 commented on src/App.jsx
> +  const handleCloseButtonClick = () => {
이렇게 한군데서 관리하셨네요😮 좋은 코드 같습니다

2024-11-06 07:54 UTC, ye6194 commented on src/components/aside/AddRestaurantModal.jsx
> +  };
카테고리가 선택되지 않거나 input, testarea가 비어있으면 경고창이 뜨게 하셨네요👍 사용자에게 명확하게 알려줄 수 있어서 좋아보여요!

2024-11-06 07:54 UTC, ye6194 commented on src/components/aside/AddRestaurantModal.jsx
> +      alert('카테코리를 선택해주세요');
오타났어용

2024-11-06 07:54 UTC, ye6194 commented on src/components/aside/AddRestaurantModal.jsx
> +  const isFilloutHandler = () => {
함수 이름을 `handleFillOut`, `validateFillOut` 등으로 고치면 더 좋지 않을까요??
예를 들어서 `isModalOpen` 같은 경우에는 **Is modal open?** -> **모달이 열렸는가?** 인데
`isFilloutHandler`은 **Is fill out handler?** -> **fill out handler인가?** 이런 느낌이어서 약간 어색해 보이기도 해요.
혜정님 생각은 어떠신가요?!

2024-11-06 07:54 UTC, ye6194 commented on src/components/common/modal/Modal.jsx
> +const Modal = ({ children, title, onCloseButtonClick }) => {
children porps를 사용하셨네요👍

2024-11-06 07:54 UTC, ye6194 commented on src/components/aside/AddRestaurantModal.jsx
> +    onSubmit((prev) => [...prev, newRestaurant]);
이렇게도 할 수 있네요!!

2024-11-06 07:54 UTC, ye6194 commented on src/components/aside/AddRestaurantModal.jsx
> +    const isFilloutAll = isFilloutHandler();
이것도 위와 같은 이유로 저는 isAllFilledOut이나 isFormComplete가 더 좋아보여요!

2024-11-06 10:18 UTC, ye6194 commented
안녕하세요 혜정님! 코드 잘 읽었습니다.

저같은 경우에는 
```js
const [isModalOpen, SetIsModalOpen] = useState(false);
const [restaurantName, setRestaurantName] = useState("");
const [restaurantInfo, setRestaurantInfo] = useState("");
const [isAddModalOpen, setIsAddModalOpen] = useState(false);
```
이렇게 isModalOpen, restaurantName, restaurantInfo, isAddModalOpen은 다른 컴포넌트도 써야하니까 App에 남겨두고 

```js
      <main>
        <CategoryFilter category={category} onChangeCategory={setCategory} />
        <RestaurantList
          restaurants={filteredRestaurants}
          SetIsModalOpen={SetIsModalOpen}
          setRestaurantName={setRestaurantName}
          setRestaurantInfo={setRestaurantInfo}
        />
      </main>
      <aside>
        {isModalOpen && (
          <RestaurantDetailModal
            SetIsModalOpen={SetIsModalOpen}
            restaurantName={restaurantName}
            restaurantInfo={restaurantInfo}
          />
        )}
        {isAddModalOpen && <AddRestaurantModal setIsAddModalOpen={setIsAddModalOpen} />}
      </aside>
```
이렇게 setIsModalOpen 등은 다른 컴포넌트로 보냈답니다. 그래서 App이 하는 일이 적은 것 같긴 한데 <main>~<aside> 부분이 약간 지저분한 것 같아요.

> 리뷰어님은 처음에 파일 구조와 컴포넌트를 구상할 때 어떤 기준으로 짜시는지 궁금합니다..!

그리고 이 부분에 답변을 하자면, 진부한 답변이긴 하지만 저는 page 폴더, component 폴더, style 폴더 등 용도에 따라 파일을 분리하고, 한 컴포넌트에는 하나의 책임만 가지도록 하고 있어요. 

이번에도 미션하시느라 수고 많으셨습니다!

2024-11-07 00:33 UTC, Songhyejeong commented on src/App.jsx
>    }
지난 번에 코드를 보니 조건을 넣었는데 굳이 else를 쓸 필요가 있을까 해서 뺐습니당 
근데 지금 보니 category !=='전체'를 없애고 if-else로 쓰는게 좋을 거 같네요!

2024-11-07 00:35 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
> +  const isFilloutHandler = () => {
그러네요! 계속 헨들러 함수 작성하다가 습관처럼 뒤에 붙인거 같습니다..
수정해야할 거 같아요!

2024-11-07 00:40 UTC, Songhyejeong commented
안녕하세요 예은님 ! 
코드 리뷰 잘 읽었습니다..! 
> 
> ```js
> const [isModalOpen, SetIsModalOpen] = useState(false);
> const [restaurantName, setRestaurantName] = useState("");
> const [restaurantInfo, setRestaurantInfo] = useState("");
> const [isAddModalOpen, setIsAddModalOpen] = useState(false);
> ```
> 
> 이렇게 isModalOpen, restaurantName, restaurantInfo, isAddModalOpen은 다른 컴포넌트도 써야하니까 App에 남겨두고
> 
> ```js
>       <main>
>         <CategoryFilter category={category} onChangeCategory={setCategory} />
>         <RestaurantList
>           restaurants={filteredRestaurants}
>           SetIsModalOpen={SetIsModalOpen}
>           setRestaurantName={setRestaurantName}
>           setRestaurantInfo={setRestaurantInfo}
>         />
>       </main>
>       <aside>
>         {isModalOpen && (
>           <RestaurantDetailModal
>             SetIsModalOpen={SetIsModalOpen}
>             restaurantName={restaurantName}
>             restaurantInfo={restaurantInfo}
>           />
>         )}
>         {isAddModalOpen && <AddRestaurantModal setIsAddModalOpen={setIsAddModalOpen} />}
>       </aside>
> ```
> 
> 이렇게 setIsModalOpen 등은 다른 컴포넌트로 보냈답니다. 그래서 App이 하는 일이 적은 것 같긴 한데
> 
> ~ 부분이 약간 지저분한 것 같아요.

함수를 넘겨서 컴포넌트의 책임이 줄어들게 하는거 좋은 거 같아요! 감사합니다!

> > 리뷰어님은 처음에 파일 구조와 컴포넌트를 구상할 때 어떤 기준으로 짜시는지 궁금합니다..!
> 
> 그리고 이 부분에 답변을 하자면, 진부한 답변이긴 하지만 저는 page 폴더, component 폴더, style 폴더 등 용도에 따라 파일을 분리하고, 한 컴포넌트에는 하나의 책임만 가지도록 하고 있어요.

좋은 답변 감사합니다! 저도 한 컴포넌트에 하나의 책임만 가지도록 구상하면서 짜는 노력을 해봐야할 거 같아요,, ! 👍

2024-11-07 22:33 UTC, Indigochi1d requested changes
step3에 이어 바로 step4 코드리뷰 진행해볼게요! 우선 모든 기능과 구현이 잘 되었습니다! 
레스토랑을 추가하는 모달에서 사용자가 입력을 하지 않을경우 예외처리 해주신 모습도 인상깊었습니다💯 

## 궁금하셨던 점에 대한 답변

> 리뷰어님은 처음에 파일 구조와 컴포넌트를 구상할 때 어떤 기준으로 짜시는지 궁금합니다..!

### 파일 구조와 컴포넌트의 구상
저는 파일구조라는 집합안에 컴포넌트 구조가 있다고 생각해요(당연한 말인가요?😄 ). 예를 들면 예은님께서 이번 리뷰에서 말씀해주신 `style`  디렉토리 라던지...`constants`과 같은 것들 자체도 파일 구조안에 들어가고 있겠죠. 
그래서 제가 가장 중요하게 생각하는 건 **컴포넌트 구조** 정도인데요.  저는 보통 애플리케이션을 만들 때 미시적으로는 컴포넌트 하나가 정확히 맡은 일만 할 수 있도록 설계하고 하는 편이에요. 구체적으로 다시 말하자면 컴포넌트 하나를 설계 할 때 컴포넌트A가 맡은 일은 컴포넌트A에서 비즈니스 로직을 수행하도록 작성해왔어요. 그렇게 해야만 흐름을 읽기 쉽고 삽질을 피하게 할 수 있다고 생각해요!
거시적으로 전체 파일구조를 생각하면..! 저는 UI의 생김새를 먼저 생각하는 편이에요. 결국 프론트엔드는 사용자의 상호작용을 하기 위해 존재하기 때문에 디자인 된 UI대로 뷰 로직을 작성한 후에 이 컴포넌트의 JSX가 더 쪼개져야하는지, 상위 컴포넌트 안에 병합해야하는지에 대한 고민을 

> `고유의 비즈니스로직을 수행하는가?` 또는 
`재사용할 수 있는 뷰로직인가?` 또는
 `뷰의 영역이 확실한가?` 

정도로 나누어서 하나만 맞아도 따로 분리하는 편입니다! 
정리해보면, 
1. UI대로 뷰 로직을 전부 만든다.
2. 컴포넌트의 책임을 찾는다.
3. 책임의 정도(view/business)와 개수에 따라 컴포넌트를 분리/병합한다.
정도로 볼 수 있겠네요😅  

### 컴포넌트의 책임에 대해서

> 구현 하다 보니까 AddRestaurantModal 컴포넌트랑, App 컴포넌트에 함수도 많고 상태도 많아서 책임이 많아 보이는 것 같네요.. 평소 궁금했던 것 중에 구현을 하다가 책임이 많아지는 것 같을 때 리팩터링을 진행했었는데 이 경우 수정이 조금 복잡해지더라구요

아마 이런 궁금증을 가지시게 된 계기를 예상해보았을 때 4단계를 하면서 `App.jsx` 에 수많은 handle함수들을 적어야 했기 때문이라고 생각해요. **구체적으론 상위 컴포넌트인 `App.jsx`에서 하위 컴포넌트인 `AddRestaurantModal` 의 비즈니스 로직(handle함수)을 작성해야하나? 어차피 실행은 하위 컴포넌트에서 할텐데..?** 라는 질문으로 받아들여집니다!
수정이 복잡하다고 느끼신 점도 아마 이런 함수들의 이름을 재정의하고 props의 전달을 전부 리팩토링해야했기 때문에 그렇게 느끼신거 같아요! 

### 🧠저만의 생각
 그래서 저는 setter함수만을넘기고 따로 handle함수로 만들어서 넘기지 않으며 애플리케이션을 만들어왔어요. 저도 이러한 고민들을 했었는데 이 때 `on~~()` , `handle~~()` 로 만들어서 넘기니까 실사용 컴포넌트인 하위 컴포넌트에 도달해서 실제로 사용해야할 때 스스로 이 함수가 어떤 `setter`함수였지? 하며 잊어버리게 되더라구요.  그래서 저는 props로 넘길때부터 setter함수 이름 그대로 넘기고 실사용하는 컴포넌트에서 그에 관한 비즈니스 로직(handle함수)을 작성하는 편이에요. 

리액트 공식문서에는 아래의 사진과 같이 `on~~()` 으로 전달하고 있지만요..ㅎ 그래서 이런 상황들에 대한 코드 컨벤션이 있는지 궁금했는데 아직 못 찾았어요😢 있다면 알려주세요!
![스크린샷 2024-11-08 005630](https://github.com/user-attachments/assets/cde16725-e459-41c4-a84a-74e3ef8ac167)

**수고하셨습니다!**

2024-11-07 22:33 UTC, Indigochi1d commented on src/App.jsx
> +  };
최상위 컴포넌트인 App.jsx 에서 너무 많은 handle함수들이 선언되고 있어요!**`실제로 하위 컴포넌트의 비즈니스 로직인데도 상위컴포넌트에서 작성 하는게 맞는가?`** 에 대한 고민을 해보셨을 거라고 생각해요! 이러한 고민들을 스터디 시간에 같이 공유하며 이야기 해보면 좋을 것 같네요!

2024-11-07 22:33 UTC, Indigochi1d commented on src/App.jsx
> +            onCloseButtonClick={handleCloseButtonClick}
요구사항대로 잘 구현해주셨네요 👍🏻

2024-11-07 22:33 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
> +  };
예외처리를 따로 해주신 모습이 보기 좋았습니다!

2024-11-07 22:33 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
> +    onSubmit((prev) => [...prev, newRestaurant]);
왜 새로운 객체(`newRestaurant`)를 만들고 spread연산자를 이용해 새로운 배열을 만드셨는지 이유를 설명해주실 수 있을까요?

2024-11-07 22:33 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
> +    e.preventDefault();
👍🏻

2024-11-07 22:33 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
> +  const [description, setDescription] = useState('');
코드를 읽어보았을 때 이 부분은 경우에 따라서 상태로 존재하지 않아도 되는 것 같아요. 

이건 제 코드인데요! 이렇게 `form`  태그에서 `onSubmit`  이벤트를 일으킬 때 그 안에 함수를 객체의 값을 불러와서 각각의 변수에 할당해주면 상태를 쓰지 않고도 할 수 있습니다!

 ```javascript
const options = ["전체", "한식", "중식", "일식", "양식", "아시안", "기타"];

const AddRestaurantModal = ({ setIsAddModal, restaurants, setRestaurants }) => {
    const onCloseAddModal = () => {
        setIsAddModal(false);
    }

    const onAddRestaurant = (e) => {
        e.preventDefault();

        const category = e.target.category.value;
        const name = e.target.name.value;
        const description = e.target.description.value;
        let icon;
        switch (category) {
            case "한식":
                icon = CategoryKorean;
                break;
            case "중식":
                icon = CategoryChinese;
                break;
            case "일식":
                icon = CategoryJapanese;
                break;
            case "양식":
                icon = CategoryWestern;
                break;
            case "아시안":
                icon = CategoryAsian;
                break;
            case "기타":
                icon = CategoryETC;
                break;
            default:
                icon = "";
                break;
        }

        const newRestaurant = {
            id: Date.now(),
            category,
            name,
            description,
            icon,
        };

        setRestaurants([...restaurants, newRestaurant]);
        onCloseAddModal();
    };

    return (
        <Modal title="새로운 음식점" onClose={onCloseAddModal}>
            <form onSubmit={onAddRestaurant}>
                <div className={`${styles.formItem} ${styles.formItemRequired}`}>
                    <label className="text-caption">카테고리</label>
                    <select name="category" required>
                        {options.map((option) => (
                            <option key={option} value={option}>{option}</option>
                        ))}
                    </select>
                </div>
                <div className={`${styles.formItem} ${styles.formItemRequired}`}>
                    <label htmlFor="name" className="text-caption">이름</label>
                    <input type="text" name="name" required/>
                </div>
                <div className={styles.formItem}>
                    <label htmlFor="description" className="text-caption">설명</label>
                    <textarea name="description" id="description" cols="30" rows="5"></textarea>
                    <span className={`${styles.helpText} text-caption`}>메뉴 등 추가 정보를 입력해 주세요.</span>
                </div>
                <div className={styles.buttonContainer}>
                    <button
                        type="submit"
                        className={`${styles.button} ${styles.buttonPrimary} text-caption}`}
                    >추가하기
                    </button>
                </div>
            </form>
        </Modal>
    );
};

export default AddRestaurantModal;
```

**category, name, description 의 선언과 form 태그를 유심히 봐주세요!**

2024-11-07 22:33 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
> +            })}
key를 idx로 주고 계신데 다른 방법이 있는지 고민해보면 좋을 것 같아요! 저번주에 저희 스터디 했던 내용을 기반으로요!

2024-11-07 22:33 UTC, Indigochi1d commented on src/components/common/modal/Modal.jsx
> +const Modal = ({ children, title, onCloseButtonClick }) => {
재사용 가능한 컴포넌트를 만들기 위해 children을 props로 받아서 addModal과 detailModal을 재구성하셨군요👏🏻

React에서는 children을 통해 컴포넌트를 재사용하는 것을 장려합니다! children은 컴포넌트가 상위 컴포넌트로부터 콘텐츠를 전달받아 자신의 구조 안에 배치할 수 있도록 도와주며, 이를 통해 개발자가 다양한 방식으로 UI를 구성할 수 있게 해요. React에서는 상속보다 컴포지션을 우선시하여 유연한 설계와 재사용 가능한 코드 작성 방식을 중시하는 철학이 반영됩니다!

따리서, 하위 컴포넌트는 어떤 콘텐츠를 받을지에 대한 정보가 없어도 다양한 맥락에서 사용될 수 있으며, 상위 컴포넌트에서 children에 적절한 콘텐츠만 넣어주면 재사용이 가능한 구조가 되는것이 장점이에요.  그럼 이렇게 사용하는 것이 무조건 장점만 있을까요? 어떻게 생각하시는지 리뷰에 대한 답변을 듣고 싶어요🦻🏻  만약 이것으로 인해 문제가 생긴다면 어떤 문제가 생길까요?

2024-11-07 22:33 UTC, Indigochi1d commented on src/components/common/modal/Modal.jsx
> +        {children}
👍🏻

2024-11-09 13:14 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
> +    onSubmit((prev) => [...prev, newRestaurant]);
둘 다 불변성 유지하는 방법이라고 알고 있어서 사용했습니다
새로운 객체를 만들어서 기존 값을 바꾸지 않고, 또한 스프레드 문법을 사용하면 복사값을 원본과 다른 메모리 주소에 할당하기 때문에 
복사본을 변경해도, 원본에 영향을 주지 않고 불변성 을 유지할 수 있다고 알고 있습니다!

2024-11-09 13:21 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
> +  const [description, setDescription] = useState('');
상태가 많으면 어떻게 해야할지 고민이었는데 상태를 쓰지 않고도 할 수 있네요! uncontrolled에 대해서 공부하고 적용해봐야겠어요
감사합니다 👍

2024-11-09 13:22 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
> +            })}
넵! 수정해보겠습니다

2024-11-09 13:40 UTC, Songhyejeong commented
안녕하세요 범수님 코드 리뷰 잘 읽었습니다!
고민 됐던 부분이 많이 해소된 것 같은 느낌이에요
리액트를 사용하면서 제 코드에 대한 리뷰를 처음 받아보는데 많이 부족함을 느꼈던 거 같습니다,,
그리고 코드 리뷰의 중요성도 다시 느끼게 되었어요! 👍 
의견 공유해주셔서 감사합니다!

> ### 파일 구조와 컴포넌트의 구상
> 저는 파일구조라는 집합안에 컴포넌트 구조가 있다고 생각해요(당연한 말인가요?😄 ). 예를 들면 예은님께서 혜정님의 코드리뷰에서 말씀해주신 `style` 디렉토리 라던지...`constants`과 같은 것들 자체도 파일 구조안에 들어가고 있겠죠. 그래서 제가 가장 중요하게 생각하는 건 **컴포넌트 구조** 정도인데요. 저는 보통 애플리케이션을 만들 때 미시적으로는 컴포넌트 하나가 정확히 맡은 일만 할 수 있도록 설계하고 하는 편이에요. 구체적으로 다시 말하자면 컴포넌트 하나를 설계 할 때 컴포넌트A가 맡은 일은 컴포넌트A에서 비즈니스 로직을 수행하도록 작성해왔어요. 그렇게 해야만 흐름을 읽기 쉽고 삽질을 피하게 할 수 있다고 생각해요! 거시적으로 전체 파일구조를 생각하면..! 저는 UI의 생김새를 먼저 생각하는 편이에요. 결국 프론트엔드는 사용자의 상호작용을 하기 위해 존재하기 때문에 디자인 된 UI대로 뷰 로직을 작성한 후에 이 컴포넌트의 JSX가 더 쪼개져야하는지, 상위 컴포넌트 안에 병합해야하는지에 대한 기준을 고민할때
> 
> > `컴포넌트가 고유의 비즈니스 로직을 수행하는가?` 또는
> > `재사용할 수 있는 뷰로직인가?` 또는
> > `뷰의 영역이 확실한가?`
> 
> 정도로 나누어서 하나만 맞아도 따로 분리하는 편입니다! 정리해보면,
> 
> 1. UI대로 뷰 로직을 전부 만든다.
> 2. 컴포넌트의 책임을 찾는다.
> 3. 책임의 정도(view/business)와 개수에 따라 컴포넌트를 분리/병합한다.
>    정도로 볼 수 있겠네요😅

자세한 설명 감사합니다! 덕분에 조금 감이 오는 것 같아요..! 
저는 UI를 먼저 만들고 나면 어떤 기준을 가지고 분리해야 할지 고민했었었는데 
지금까지 컴포넌트가 각자 어떤 책임을 가져야하는지에 대한 고민이 부족했었던 거 같아요.,,

컴포넌트가 고유한 비지니스 로직을 수행하는지, 각 컴포넌의 책임을 찾는 과정이 너무 좋은 거같아요! 
꼭 필요한 과정이라고 생각해요! 말씀해주신대로 앞으로 적용해가며 연습해보겠습니다! 감사합니다 👍 


> ### 컴포넌트의 책임에 대해서
> > 구현 하다 보니까 AddRestaurantModal 컴포넌트랑, App 컴포넌트에 함수도 많고 상태도 많아서 책임이 많아 보이는 것 같네요.. 평소 궁금했던 것 중에 구현을 하다가 책임이 많아지는 것 같을 때 리팩터링을 진행했었는데 이 경우 수정이 조금 복잡해지더라구요
> 
> 아마 이런 궁금증을 가지시게 된 계기를 예상해보았을 때 4단계를 하면서 `App.jsx` 에 수많은 handle함수들을 적어야 했기 때문이라고 생각해요. **구체적으론 상위 컴포넌트인 `App.jsx`에서 하위 컴포넌트인 `AddRestaurantModal` 의 비즈니스 로직(handle함수)을 작성해야하나? 어차피 실행은 하위 컴포넌트에서 할텐데..?** 라는 질문으로 받아들여집니다! ~아니라면 당근이모지를...~ 수정이 복잡하다고 느끼신 점도 아마 이런 함수들의 이름을 재정의하고 props의 전달을 전부 리팩토링해야했기 때문에 그렇게 느끼신거 같아요!
> 

맞아요! App.jsx에서 handle함수를 작성해야하는지, 아니면 하위 컴포넌트에서 작성해야하는지 고민이었어요
정확한 저만의 기준이 없어서 그랬던 거 같습니다,,

> ### 🧠저만의 생각
> 그래서 저는 setter함수만을넘기고 따로 handle함수로 만들어서 넘기지 않으며 애플리케이션을 만들어왔어요. 저도 이러한 고민들을 했었는데 이 때 `on~~()` , `handle~~()` 로 만들어서 넘기니까 실사용 컴포넌트인 하위 컴포넌트에 도달해서 실제로 사용해야할 때 스스로 이 함수가 `setter`함수였나? 하며 잊어버리게 되더라구요. 그래서 저는 props로 넘길때부터 setter함수 이름 그대로 넘기고 실사용하는 컴포넌트에서 그에 관한 비즈니스 로직(handle함수)을 작성하는 편이에요.
> 

이 방법 좋은 거 같습니다! 예은님도 말씀해주신건데 setter함수만 넘기게 되면 handle 함수를 작성하지 않아도 되고,
계속해서 하위 컴포넌트로 넘기다 보면 어떤 함수를 넘겼었는지 찾기 힘들게 되더라고요 

> 리액트 공식문서에는 아래의 사진과 같이 `on~~()` 으로 전달하고 있지만요..ㅎ 그래서 이런 상황들에 대한 코드 컨벤션이 있는지 궁금했는데 아직 못 찾았어요😢 있다면 알려주세요! ![스크린샷 2024-11-08 005630](https://private-user-images.githubusercontent.com/33516980/384151163-cde16725-e459-41c4-a84a-74e3ef8ac167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTg0NzAsIm5iZiI6MTczMTE1ODE3MCwicGF0aCI6Ii8zMzUxNjk4MC8zODQxNTExNjMtY2RlMTY3MjUtZTQ1OS00MWM0LWE4NGEtNzRlM2VmOGFjMTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDEzMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MTBkZWRjYjZlNjc0YTk3YzhmN2M4MWE4ODFjYjc3MjdhY2I4ZmRmODA2YmQwYjEzZjU5MzYwNGUyZDIzZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mrSKMvxzOaUt9VOrurzbz8n5QD8FmPfSNyS1kXviF-s)
> 
> **수고하셨습니다!**

감사합니다!! 저도 코드 컨벤션이 있는지 찾으면 다음 스터디에서 공유하겠습니다!

2024-11-09 13:48 UTC, Songhyejeong commented
그리고 children에 대해서 생각해본 건, 


> 따리서, 하위 컴포넌트는 어떤 콘텐츠를 받을지에 대한 정보가 없어도 다양한 맥락에서 사용될 수 있으며, 상위 컴포넌트에서 children에 적절한 콘텐츠만 넣어주면 재사용이 가능한 구조가 되는것이 장점이에요. 그럼 이렇게 사용하는 것이 무조건 장점만 있을까요? 어떻게 생각하시는지 리뷰에 대한 답변을 듣고 싶어요🦻🏻 만약 이것으로 인해 문제가 생긴다면 어떤 문제가 생길까요?

약간 가독성 측면에서 어떤 jsx가 렌더링 되는지 한 눈에 알 수 없다는 점이 단점인 것 같아요..! 
그리고 다른 컴포넌트에서도 children을 많이 사용하다보면 헷갈릴 수도 있을 거 같네요
하지만 범수님이 말씀해주신거 처럼 그만큼 자유롭게 상위 컴포넌트에서 설정하고 사용할 수 있어서
재사용성과 유연성 측면에서는 큰 장점이 될 수있는 것 같습니다..!

2024-11-09 13:48 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
> +  };
감사합니다!

2024-11-09 18:21 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
> +    onSubmit((prev) => [...prev, newRestaurant]);
그렇다면 리액트를 사용할때 불변성을 지켜야하는 이유는 뭘까요? 불변성을 강조하는 이유는 뭘까요?

2024-11-10 01:15 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
> +    onSubmit((prev) => [...prev, newRestaurant]);
저는 불변성을 지키지 않으면 예상치 못한 상태 변화가 일어나기 때문
이 정도로만 알고 사용하고 있었는데 찾아보니 리액트에서 이전 상태와 비교하여 렌더링을 할 때 얕은 비교를 하는데 
이게 객체나 배열의 실제 값을 비교하는게 아니라 참조 주소만 비교한다고 하네요. 
근데 이렇게 되면 불변성을 유지하지 않을 경우 내부 값을 변경하기 때문에 참조 값은 변경 되지 않아, React가 렌더링을 할 때 상태 변화를 올바르게 감지하지 못하게 될 거 같네요..! 상태 변화를 감지하지 못하고 결국 계속 새로운 상태는 무시한 채, 이전 상태로만 렌더링 될 거 같습니다...!

2024-11-10 08:21 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
> +    onSubmit((prev) => [...prev, newRestaurant]);
💯

2024-11-10 08:21 UTC, Indigochi1d approved these changes

2024-11-10 12:39 UTC, Indigochi1d approved these changes

2024-11-10 12:40 UTC, merged