[4단계] 김준수 미션제출합니다.
cho-log/self-paced-react pull request #32
Opened 2024-11-05 14:15 UTC by gogo1414

### 개요
안녕하세요, 리뷰어님
4단계 미션은 3단계 미션의 약간 연장이라고 느껴졌네요! 재사용 가능한 컴포넌트라는 개념이 신기했습니다😊

### 호기심
컴포넌트를 재사용한다는 개념이 매우 신기했는데, 나중에 재사용하는 모달이 많을 경우 관리가 따로 필요해보이는 생각이 들었는데 어떻게 생각하시나요?
(아직 제가 익숙하지 않아서 매우 생소하게 느껴지는걸 수도 있어요...)

### 작업 내용
1. 레스토랑 추가 모달 생성
2. 레스토랑 추가 시 레스토랑 리스트에 데이터 적재
3. 재사용 가능한 `Modal` 컴포넌트 구현

### 참고 스터디 링크
- [API Reference: <input>](https://react.dev/reference/react-dom/components/input)

### Image
<img width="976" alt="스크린샷 2024-11-05 오후 11 10 35" src="https://github.com/user-attachments/assets/adbd10c3-91d5-48fe-ab46-a0131977bac3">
<img width="976" alt="스크린샷 2024-11-05 오후 11 10 38" src="https://github.com/user-attachments/assets/167a9f09-a078-4336-8ced-a07e2529b37e">

### Directory Structure
<img width="667" alt="스크린샷 2024-11-05 오후 11 12 29" src="https://github.com/user-attachments/assets/ca4410f3-f7c7-4b65-a165-bcdb4c36aebd">
- `AdRestaurantModal`의 데이터도 분리해서 양방향으로 표시하려고 화살표를 없앴어요!

### 느낀점
1. 컴포넌트를 재사용한다는 개념이 매우 신기했고 확실히 중복되는 코드들이 줄어서 포기 편했어요!!

2024-11-06 10:18 UTC, Songhyejeong reviewed
안녕하세요 준수님!

> 컴포넌트를 재사용한다는 개념이 매우 신기했는데, 나중에 재사용하는 모달이 많을 경우 관리가 따로 필요해보이는 생각이 들었는데 어떻게 생각하시나요?
(아직 제가 익숙하지 않아서 매우 생소하게 느껴지는걸 수도 있어요...)

나중에 재사용하는 모달이 많을 경우에는 말씀하신 거 처럼 관리를 따로 하면 좋을 거 같네요!
그 경우에는 isModalOpen과 같은 모달의 열고 닫는 상태까지 재사용 가능한 Modal 컴포넌트에서 관리하면 App에서 많은 상태를 만들지 않고도 관리할 수 있을 거 같네요!

4단계 미션까지 고생하셨습니다 👍

2024-11-06 10:18 UTC, Songhyejeong commented on src/App.jsx
> +  });
모달을 객체로 나눠서 관리하는 방법은 생각하지 못했는데 새롭네요!

2024-11-06 10:18 UTC, Songhyejeong commented on src/App.jsx
> +      <Header onChangeAddModal={openAddModal}/>
react에 이벤트가 onClick, onChange, onSubmit 이렇게 있어서 
함수 명을 전달할 때 앞에 on을 붙이는 것이 일반적인데 이 경우는
header를 `click`하는 이벤트를 전달하는 것이니
```suggestion
      <Header onClickAddModal={openAddModal}/>
```
이렇게 바꾸면 클릭하는 이벤트를 실행할 것이다 라고 알아채기 쉬울 거 같아요! 
그리고 이벤트를 처리하는 함수에는 handle을 붙이는 것이 일반적이라고 합니다!

2024-11-06 10:18 UTC, Songhyejeong commented on src/App.jsx
> +  }
지금 setIsModalOpen이 4개의 함수에서 실행돼서 하나로 합칠 수 있어 보이는데 isOpen, (add,detail -> type) 과같은 애들을 인자로 전달해서 하나로 합쳐 보면 어떨까요?

2024-11-06 10:18 UTC, Songhyejeong commented on src/App.jsx
> +  }
addRestaurant 함수를 App에서 저장하는 방법도 있었군요..
저는 그냥 input과 text 값이 계속 변하고 AddRestaurantModal 컴포넌트와 관련된 함수니 AddRestaurantModal에서 관리해야겠다고 생각했는데,
준수님 처럼 하는 것이 더 좋을 수도 있을 거 같네요.. 이 부분은 더 고민해봐야 할 거 같아요,,

2024-11-06 10:18 UTC, Songhyejeong commented on src/components/Aside/AddRestaurantModal.jsx
> +            <form method="post" onSubmit={(event) => onChangeAddModal(event.target)}>
이 부분에서 onChangeAddModal로 event 값을 전달하는 것 대신
onSubmit 함수를 App 에서 따로 만들어 관리하는 것은 어떨까요?

그리고 이건 사소한건데 onChangeAddModal 대신 close 하는 것이 명확하니 handleCloseModal로 함수명을 변경하는 것도 생각해보시면 좋을 거 같아요!
```suggestion
            <form method="post" onSubmit={(event) => onFormSubmit(event.target)} >
```

2024-11-06 10:18 UTC, Songhyejeong commented on src/components/Aside/AddRestaurantModal.jsx
> +                    <button className={`${styles.button} ${styles["button--primary"]} text-caption`}>추가하기</button>
```suggestion
                    <button className={`${styles.button} ${styles["button--primary"]} text-caption`} onClick ={onChangeModal}>추가하기</button>
```
위에 함수를 onFormSubmit으로 바꿔서 이부분을 추가했습니다..! 이런식으로 해도 좋을 거 같아요

2024-11-07 08:15 UTC, gogo1414 commented on src/App.jsx
> +      <Header onChangeAddModal={openAddModal}/>
이것도 네이밍을 과거로 하는게 좋을까요?? `onClickedAddModal` 이렇게요!

2024-11-07 08:16 UTC, gogo1414 commented on src/App.jsx
> +  }
합치면 저도 좋을거 같은데 어떻게 합쳐야할 지 감이 안와서 이렇게 했었네요.. 모달을 각각 변수로 나눠서 진행은 했었는데 이 부분은 도저히 생각이 안나네요...

2024-11-08 02:07 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +            <form method="post" onSubmit={(event) => onChangeAddModal(event.target)}>
값 전달과 모달 창을 닫는 것을 분리하시라는 말씀이신거죠??
좋은 방법 같네요!!

2024-11-08 02:31 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +                    <button className={`${styles.button} ${styles["button--primary"]} text-caption`}>추가하기</button>
분리해보니 정보를 추가하지 않고 추가버튼 눌렀을 때 그냥 닫히는 문제가 생기더군요... 조금 고민해봐야 될거 같아요

2024-11-09 14:54 UTC, wzrabbit requested changes
@gogo1414 👋🏻 

4단계 미션 구현도 수고하셨습니다. 이 단계가 여러모로 복잡할 거라 생각해요. 프론트엔드에서는 꽤 복잡한 도메인에 속하는 폼 관리도 해 주어야 하고, 재사용에 대한 고민을 해야하는 단계이기도 하거든요. 저도 컴포넌트를 구현할 때마다 자주 가만히 있으면서 생각에 잠기는 시간이 많답니다. 컴포넌트의 재사용에 대한 고민은 프론트엔드 분야를 하는 한 피해갈 수 없는 고민이기도 해요.

## 1️⃣ 리뷰
3단계와 합쳐서 직접 조작해보았는데 잘 작동하는 것 같아요 👍🏻 `<form>` 을 사용해주셔서 그런지 카테고리를 안 골랐거나 이름을 안 적었을 때 음식점을 추가하려고 하면 막히던데 HTML 태그를 잘 활용해주셨어요.

폼 제출에서부터 데이터가 추가되는 과정은 개선이 필요해보인다는 생각이 들었어요. 폼을 제출한 이후 `App` 에서 직접 자식 컴포넌트의 DOM을 `FormData`를 이용해 접근해 주신 후 데이터를 가져오고 계신데, 부모 컴포넌트가 하는 일이 너무 많을 수 있다는 생각이 들었고, 한편으로는 자식 컴포넌트에서 직접 가져오는 요소가 있다보니 위험할 수도 있다는 생각 또한 들었습니다. 자식이 할 수 있는 일은 자식에게 맡기는 것도 좋은 방법이 될 수 있다고 생각해요.

모달 컴포넌트의 재사용의 경우 의도에 맞게 잘 구현해주셨다고 생각해요. 프론트엔드 프로젝트에서 모달은 대부분의 상황에서 정말 빠질 수 없는 요소인데, 문제는 모달에 나타나는 내용과 기능은 정말 제각각일 수 있다는 거에요. 하지만 그럼에도 불구하고 대부분의 모달이 *공통적으로 수행하는 기능**, **공통적으로 지니는 UI** 등을 지녀요. 이 부분을 캐치하셔서 더 원시적인 범위의 컴포넌트를 만들어보셨다면 더 컴포넌트를 재사용하기 용이하게 하고 그만큼 반복적으로 해야 할 작업들이 많이 줄어드는 것이 체감되실 거에요.

> 나중에 재사용하는 모달이 많을 경우 관리가 따로 필요해보이는 생각이 들었는데 어떻게 생각하시나요?

단순히 메시지만 보여주고 끝나는 모달이었으면 좋았겠지만, 모달이란 게 이번에 재사용하신 모달의 **틀** 뿐만 아니라 내부 요소에서도 겹치는 UI들이 정말 많아요. 예를 들면, 모달에서 여러 개를 체크할 수 있는 체크박스라든지, 모달 하단에 생기는 여러 버튼들의 집합들이 있겠죠.

모달의 특성상 **UI는 비슷한 요소를 여러 번 활용하나 최종 UI는 제각각**인 경우가 많아요, 이에 효과적으로 대응하기 위해서는 컴포넌트를 조금 더 작은 범위로 쪼갠 후, 작은 범위의 컴포넌트를 조합해 더 큰 컴포넌트를 용도에 맞게 만들어내는 식으로 대응한다면 유지보수에 용이하도록 관리하실 수 있을 거라 생각해요.

인사이트를 얻어가실 수 있도록, **합성(composition)** 을 적극 이용해 다양한 요구사항 속에서 어떻게 모달 컴포넌트를 대처해서 구현하고 있는지를 다룬 글을 올려드리고자 해요.
- https://fe-developers.kakaoent.com/2021/211022-react-children-tip/

저는 여기까지! 여러 코멘트를 적어보았습니다만, 제 리뷰가 준수님께 유용했으면 좋겠는 바램입니다.

2024-11-09 14:54 UTC, wzrabbit commented on src/App.jsx
> +  const [ restaurantList, setRestaurantList ] = useState(Restaurants());
레스토랑의 더미 데이터/초기 데이터를 이러한 방식으로 사용하시려고 했던 것 같아요.
우선 사용 방법은 좋습니다만, 네이밍 측면에서 개인적으로 `Restaurants()` 가 생소하게 느껴졌고, 의도를 파악하기 어려웠던 것 같아요. 아래에 이유를 적어 볼게요.

1. 파스칼 케이스: `Restaurants`은 파스칼 케이스죠? 파스칼 케이스가 보통 컴포넌트, 클래스에 사용된다고 생각했을 때 여기에서는 클래스로 보기 쉬울 것 같아요. 하지만 실제로는 함수죠?
2. 함수 사용: `Restaurants`는 인자를 받아 동적인 값을 반환하는 것이 아니면서, **정적인 값을 반환**하는 것 외에 함수로써 필요한 아무 작업을 하지 않고 있어요. 그렇다면 함수여야 할 특별한 이유가 있을까요? 단순 오브젝트로도 사용할 수 있다고도 생각해요.
3. 명사형 이름: `Restaurants`는 함수임에도 명사형 이름을 사용하고 있어, `Restaurants`가 함수라는 것을 파악하기 어려울 것 같아요. 만약 함수로 사용하시고 싶으시다면 `getRestaurants` 와 같이 동사형 네이밍이면 이 함수가 어떤 동작을 하는지 더 명확해질 수 있다고 생각하고 있어요.
4. 의미: `Restaurants`는 비슷한 이름을 사용하고 있는 `restaurantList` 와 혼동할 수 있어보인다고 생각해요. `Restaurants`가 `restaurantList`와 달리 **초깃값**, **더미 데이터** 등의 목적으로 사용된다는 의미를 더하면 어떨까요?

이를 종합했을 때 어떻게 생각하시나요?

2024-11-09 14:54 UTC, wzrabbit commented on src/App.jsx
> +    setIsModalOpen((prev) => ({ ...prev, [modalType]: isOpen }));
상태 업데이트 시 굉장히 중요하고 좋은 로직을 적어주셨어요 👍🏻 👍🏻 다만 의도를 파악하신 채로 사용하셨는지 여쭤보고 싶어요 😈 
```
setMyState((prev) => ~~~);
```
는
```
setMyState(~~~);
```
와 비교했을 때 어떤 차이가 있을까요?

2024-11-09 14:54 UTC, wzrabbit commented on src/App.jsx
> +            onFormSubmit={(event) => toggleModal("add", false, null, event)}
`toggleModal`이 하는 일이 방대해짐에 따라 많은 매개변수를 입력으로 받고 있는 것 같군요? 도메인에 따라 좀 복잡한 일을 해야 하면 여러 종류의 값을 파라미터에 넣는 일도 있을 때가 있죠...!

다만, 파라미터가 늘어나면 늘어날수록 각 파라미터가 무슨 일을 하는지는 점점 희미해지기 시작하고, 개발자가 실수로 파라미터를 넣는 순서를 틀리기도 할 수 있다고 생각해요.

그래서 파라미터가 많아져도 각 파라미터가 무슨 역할을 하는지 이해하기 쉽도록 하기 위해, **오브젝트**를 이용해 개선해 볼 수 있다고 생각하는 데, 어떤가요?

```js
onFormSubmit={(event) => {
  toggleModal({
    modalType: "add",
    isOpen: false,
    detailData: null,
    event
  });
};
```

그 외에도, 이렇게 여러 매개변수를 사용하는 케이스가 많다면 하나의 함수가 너무 많은 기능을 맡고 있지는 않은가도 고민해 보시기에 좋을 것이라고 생각해요.

2024-11-09 14:54 UTC, wzrabbit commented on src/App.jsx
> +    setRestaurantList([...restaurantList, newRestaurant]);
`FormData` Web API를 이용해 자식 컴포넌트인 `<AddRestaurantModal>` 의 DOM에 직접 접근하고 계신 것 같은데, `App` 의 입장에서 자식 컴포넌트의 DOM 정보를 알아야 할까요? 어쩌면 숫자야구에서 컨트롤러가 의도되지 않은 모델의 멤버 변수들에 접근하는 형태와도 비슷해 보이는 것 같아요.

지금은 자식 컴포넌트의 요소를 직접 가져오는 것에 그쳤지만, 자식 컴포넌트에 어떤 상황이 발생했는지 모르는 상태에서 자식 컴포넌트의 도움을 받지 않고 그대로 대처를 하는 방법은 어쩌면 위험할 수도 있어보여요. 여기에 한술 더 떠 만약 자식 컴포넌트의 요소를 직접 조작하기라도 한다면 자식 컴포넌트의 동작을 방해할 수도 있어보이고요.

자식 컴포넌트가 할 수 있는 일이고, 로직 또한 자식 컴포넌트와 가까이 있다면, 자식 컴포넌트에게도 일을 맡겨 보셔도 좋을 것 같아요.

2024-11-09 14:54 UTC, wzrabbit commented on src/components/Aside/Modal.jsx
> +export default Modal;
모달 컴포넌트 인상깊게 잘 봤습니다. 대부분의 웹 프로젝트에서는 모달을 정말 지겹도록 많이 쓸 텐데요, 각각의 모달은 제각각의 기능을 지니고 있지만 기본적인 모달로써의 동작은 공통적인 부분이 많을 거에요. 예를 들면 모달을 열고 닫을 때의 애니메이션이라든지, 모달의 빈 부분을 누르거나 닫기 버튼을 누를 때의 닫는 동작들 등등...이요. 구현해주신 모달 컴포넌트는 범용성이 높고 어느 모달을 구현하더라도 기초적인 기반이 되는 컴포넌트로써 잘 사용될 수 있을 것이라 생각해요.

 `children` prop도 적절히 이용해 주셨는데, `children` prop은 외형적으로 자연스러울 뿐만 아니라 부모 컴포넌트를 마치 재사용 가능한 "틀" 처럼 사용해 재사용성을 강화시킬 수 있도록 컴포넌트를 디자인할 수 있어요. 지금처럼 내부에 들어가는 데이터가 유연할 때에도 좋아요.

2024-11-09 14:54 UTC, wzrabbit commented on src/components/Aside/AddRestaurantModal.jsx
> +                            <option key={category.id} value={category.name}>{category.name}</option>
## 인터뷰 🎤 
`key` 값으로 `category.id` 를 골라주신 이유가 있으신가요?

2024-11-09 14:54 UTC, wzrabbit commented on src/components/Aside/AddRestaurantModal.jsx
## 인터뷰 🎤 
1. 제어 컴포넌트(controlled components)와 비제어 컴포넌트(uncontrolled components)란 뭘까요? 둘의 방식은 각각 어떠한가요?
2. `<AddRestaurantModal>` 의 인풋과 폼은 제어 컴포넌트로써 관리되고 있을까요, 비제어 컴포넌트로써 관리되고 있을까요? 그 이유는 무엇일까요?

2024-11-11 06:21 UTC, gogo1414 commented
> 폼 제출에서부터 데이터가 추가되는 과정은 개선이 필요해보인다는 생각이 들었어요. 폼을 제출한 이후 `App` 에서 직접 자식 컴포넌트의 DOM을 `FormData`를 이용해 접근해 주신 후 데이터를 가져오고 계신데, 부모 컴포넌트가 하는 일이 너무 많을 수 있다는 생각이 들었고, 한편으로는 자식 컴포넌트에서 직접 가져오는 요소가 있다보니 위험할 수도 있다는 생각 또한 들었습니다. 자식이 할 수 있는 일은 자식에게 맡기는 것도 좋은 방법이 될 수 있다고 생각해요.

- 데이터의 흐름을 보았을 때 레스토랑의 정보가 부모 컴포넌트에서 자식 컴포넌트로 전달이되고 자식 컴포넌트에서 사용자가 새롭게 입력한 정보들을 바탕으로 새로운 레스토랑이 탄생하게 되는데 추가된 레스토랑의 정보는 부모 컴포넌트 내에서 보여지게 됩니다. 
그래서 제가 생각하기에는 자식 컴포넌트에서 발생한 이벤트가 부모 컴포넌트에 영향을 미치는게 올바르지 않다고 느껴져서 부모 컴포넌트에서 실행이 되도록 구현을 진행했는데 제가 생각한 자식 컴포넌트가 부모 컴포넌트에 영향을 미치는게 올바르지 않다는게 사실 잘못된걸까요..?

> > 나중에 재사용하는 모달이 많을 경우 관리가 따로 필요해보이는 생각이 들었는데 어떻게 생각하시나요?
> 
> 단순히 메시지만 보여주고 끝나는 모달이었으면 좋았겠지만, 모달이란 게 이번에 재사용하신 모달의 **틀** 뿐만 아니라 내부 요소에서도 겹치는 UI들이 정말 많아요. 예를 들면, 모달에서 여러 개를 체크할 수 있는 체크박스라든지, 모달 하단에 생기는 여러 버튼들의 집합들이 있겠죠.
> 
> 모달의 특성상 **UI는 비슷한 요소를 여러 번 활용하나 최종 UI는 제각각**인 경우가 많아요, 이에 효과적으로 대응하기 위해서는 컴포넌트를 조금 더 작은 범위로 쪼갠 후, 작은 범위의 컴포넌트를 조합해 더 큰 컴포넌트를 용도에 맞게 만들어내는 식으로 대응한다면 유지보수에 용이하도록 관리하실 수 있을 거라 생각해요.
> 
> 인사이트를 얻어가실 수 있도록, **합성(composition)** 을 적극 이용해 다양한 요구사항 속에서 어떻게 모달 컴포넌트를 대처해서 구현하고 있는지를 다룬 글을 올려드리고자 해요.
> 
> * https://fe-developers.kakaoent.com/2022/220731-composition-component/
> 
> 저는 여기까지! 여러 코멘트를 적어보았습니다만, 제 리뷰가 준수님께 유용했으면 좋겠는 바램입니다.

더 작은 컴포넌트들을 조합해서 사용한다는게 사실 너무 번거로운 일이라고 느껴져서 굳이 그렇게 해야할까? 라는 생각이 들었는데 보내주신 사이트의 글을 읽고 "이래서 작은 컴포넌트들을 조합해 하나의 합성 컴포넌트로 사용하는구나!" 하고 바로 깨달음을 얻었습니다!

내가 혼자서 모든 것을 만드는 개발자라면 상관 없겠지만 회사 혹은 사이드 프로젝트를 진행함에 있어 개발을 하는 것은 나 혼자만이 아니고 추가되는 사항이 존재할 수 있으니 이러한 것들을 고려해서 개발을 해야한다는 것을 다시 한번 상기하게 되네요! 

좋은 글 공유 감사합니다.

2024-11-11 06:24 UTC, gogo1414 commented on src/App.jsx
> +  const [ restaurantList, setRestaurantList ] = useState(Restaurants());
자바스크립트의 특성(?) 때문인지는 몰라도 제가 구분해서 생각을 잘 못했습니다...
레스토랑의 정보 객체가 존재하고 해당 객체의 데이터를 가져오는 형식이기 때문에 `getRestaurants()`라는 표현이 더 올바른거 같네요!

레스토랑 객체와 정보를 주입하는 로직을 따로 분리하는게 좋은 방법으로 생각되네요...!

2024-11-11 06:26 UTC, gogo1414 commented on src/App.jsx
> +    setIsModalOpen((prev) => ({ ...prev, [modalType]: isOpen }));
제 생각으로는 위의 (prev) => ~~~~ 가 존재하는 경우 이전 상태 값을 가져와서 사용이 가능하지만, 아래의 ~~~만 있는 경우 이전 상태 값을 가져오지 않고 현재의 정보만 기록한다고 알고 있습니다!

즉, 이전 상태 값을 참조할 수 있는지 없는지에 차이가 존재하는거 같네요!

2024-11-11 06:31 UTC, gogo1414 commented on src/App.jsx
> +            onFormSubmit={(event) => toggleModal("add", false, null, event)}
사실 저 4개의 매개변수를 받는 함수 자체를 다른 방법으로 바꾸고 싶어요! 
현재 단순 값만 들어가 있어서 어떤 동작을 수행하는지 예측이 불가능해서 코드를 작성하면서 저도 불편한 점이 있었어요...

접근을 어디서부터 해야할 지 살짝 막막하긴 한데 고민 해보겠습니다...

2024-11-11 06:32 UTC, gogo1414 commented on src/App.jsx
> +    setRestaurantList([...restaurantList, newRestaurant]);
이 부분은 5단계에서 정보만 전달하도록 수정하긴 했는데, 해당 관련 고민이 있는 내용을 총 코멘트(?)에 작성했습니다!

제가 잘못 알고 있는지에 대해 알려주시길 부탁드립니다😂

2024-11-11 06:34 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +                            <option key={category.id} value={category.name}>{category.name}</option>
저번 스터디를 진행했을 때 key값을 임의(index 등)로 넣었을 때 생기는 (리)렌더링 관련 문제에 대해 배웠는데 해당 문제를 피하기 위해 id 값을 카테고리에 따로 만들어서 사용하고자 했습니다!

2024-11-11 06:55 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> 1. 제어 컴포넌트(controlled components)와 비제어 컴포넌트(uncontrolled components)란 뭘까요? 둘의 방식은 각각 어떠한가요?

- 제어 컴포넌트는 React에 의해 값이 제어되는 입력 폼 엘리먼트를 의미합니다. 컴포넌트의 state 속성에 의해 유지되며 setState()에 의해 업데이트 됩니다.

- 비제어 컴포넌트는 DOM(Document Object Model) 자체에서 폼 데이터가 다루어지는 것을 의미합니다. ref를 사용하여 DOM에서 폼 값을 직접 가져와 사용됩니다.

참고 자료
- [제어 컴포넌트](https://ko.legacy.reactjs.org/docs/forms.html#controlled-components)
- [비제어 컴포넌트](https://ko.legacy.reactjs.org/docs/uncontrolled-components.html)
- [Ref와 DOM](https://ko.legacy.reactjs.org/docs/refs-and-the-dom.html)

> 2. <AddRestaurantModal> 의 인풋과 폼은 제어 컴포넌트로써 관리되고 있을까요, 비제어 컴포넌트로써 관리되고 있을까요? 그 이유는 무엇일까요?

- ref를 사용해서 가져오는 방식이 아니라 setState에 의해 업데이트 되는 방식이니 제어 컴포넌트라고 생각합니다.

2024-11-11 07:52 UTC, Indigochi1d commented on src/App.jsx
> +    setIsModalOpen((prev) => ({ ...prev, [modalType]: isOpen }));
부연설명을 해보자면 상태 업데이트 함수(setter함수)에서는 **두 가지 방식**이 있어요.
## 1.직접 값 설정
아래의 코드와 같이 값을 직접 전달하는 방식이 있고 이 녀석은**이전 상태를 신경 쓸 필요 없이** 새로운 값이 설정돼요.
```javascript
setIsModalOpen({ detail: true, add: false });
```
눈치채셨겠지만 이전 상태에 의존하지 않을 경우에 사용해요. 그냥 `너가 뭐였던 간에 너 이거해` 라고 해버리는거죠. 
## 2. 함수로 상태 업데이트
이 방식에서는 이전 상태에 기반한 값을 업데이트해야할 때 사용해요. 인수로 전달되는 값은 객체의 바로 (업데이트되었을때 시점에서)이전 상태입니다.
```javascript
setIsModalOpen((prev) => ({ ...prev, detail: true }));
```
이 녀석은 이전 상태를 기반으로 새로운 상태를 계산합니다. 따라서 상태가 이전 상태에 따라 결정되어야할 때 유용해요.

`modalType`에 따라 모달의 상태만 변경하는 로직이기에 `이전 상태`를 필요로 하고 그렇기에 함수형 업데이트가 사용되는 것이 적합해보이네요!!

설명이 부족했을 수 있으니 의천님이 추가 설명해주시면 저도 하나 배워가겠습니다!😄

2024-11-11 13:44 UTC, wzrabbit approved these changes
> 데이터의 흐름을 보았을 때 레스토랑의 정보가 부모 컴포넌트에서 자식 컴포넌트로 전달이되고 자식 컴포넌트에서 사용자가 새롭게 입력한 정보들을 바탕으로 새로운 레스토랑이 탄생하게 되는데 추가된 레스토랑의 정보는 부모 컴포넌트 내에서 보여지게 됩니다.
그래서 제가 생각하기에는 자식 컴포넌트에서 발생한 이벤트가 부모 컴포넌트에 영향을 미치는게 올바르지 않다고 느껴져서 부모 컴포넌트에서 실행이 되도록 구현을 진행했는데 제가 생각한 자식 컴포넌트가 부모 컴포넌트에 영향을 미치는게 올바르지 않다는게 사실 잘못된걸까요..?

자식 컴포넌트가 부모 컴포넌트의 데이터 갱신을 위해 **요청**해 주는 기존의 로직은 괜찮습니다! 이미 설명해드렸듯이 단방향 원칙을 위반하는 경우도 아니에요. 그러니 이후 문제가 발생하더라도 어느 컴포넌트에 문제가 발생했는지 알아내기에 좋은 구조일 것입니다.

우려했던 부분은 자식 컴포넌트인 `<AddRestaurantModal>`이 하면 좋을만한 **FormData API를 위해 요소에 직접 접근해 데이터를 직접 취합하는 과정** 을 부모 컴포넌트인 `<App>`에서 하고 있었던 점이었습니다. 아래의 취약점이 예상되기 때문입니다.
- `<App>`이 `<AddRestaurantModal>` 의 구성 요소를 알아야 하는 문제가 있습니다. `<App>`이 이것까지 해야 할까요? 데이터를 취합하는 과정은 자식 컴포넌트인 모달 컴포넌트가 충분히 할 수 있는 작업이 아닐까요?
- 직접 자식 컴포넌트의 요소에 접근 및 수정을 가하는 경우에는 자식 컴포넌트의 동작을 방해할 수 있으며, 자식 컴포넌트의 관할이 아니기 때문에 자식 컴포넌트에서의 자체적인 예외 처리 및 피드백을 기대할 수 없게 됩니다.
- 유지보수에 힘든 구조가 될 수 있습니다. 자식 컴포넌트가 부모 컴포넌트의 updater function을 호출하면서 데이터만 넘겨준다면 이후 자식 컴포넌트의 구조나 기능이 변경되더라도 전달하는 데이터의 형식만 동일하면 문제가 없습니다. 그러나 부모 컴포넌트가 자식 컴포넌트의 요소에 직접 접근하는 방법은 이후 자식 컴포넌트의 기능이나 구조가 달라질 경우 잘못 작동할 수 있으며, 부모 컴포넌트 및 자식 컴포넌트를 비교하면서 다시 수정을 가해야 합니다.

이번에 Step 5에서 반영하신 코드에 대해 제가 보는 걸 원하셔서 봤습니다만 훨씬 구조가 좋아진 것 같아요. 폼에서의 데이터를 취합하는 과정이 모달 컴포넌트로 옮겨져서, 부모 입장에서는 자식 컴포넌트의 내부 구조를 알 필요 없이 updater function만 넘겨주면 되는 구조가 되었어요 🎉 

이외에 반영해주신 코멘트들도 잘 보았고요, 많은 개선을 해 주시느라 고생 많으셨어요. 앞으로도 새로운 내용을 배우더라도 컴포넌트의 역할 및 사용성 등은 굉장히 중요한 토픽이기 때문에 앞으로도 계속 언급할 예정이에요.

Step 3, 4 진행하시느라 수고 많으셨어요! 👍🏻

2024-11-11 13:44 UTC, wzrabbit commented on src/data/Restaurant.js
> +}
이러한 로직을 만들어주시는 거라면, `class` 의 사용은 어떠세요?

2024-11-11 13:44 UTC, wzrabbit commented on src/App.jsx
> +  const [ restaurantList, setRestaurantList ] = useState(getRestaurants());
수고하셨습니다~ 👍🏻 casing과 네이밍만 잘 준수되도 내부를 보지 않고 상당 부분 역할이 예측되는 것 같아요.

2024-11-11 13:44 UTC, wzrabbit commented on src/components/Aside/AddRestaurantModal.jsx
### 1️⃣ 
그렇습니다. 다르게 말하면 **비제어 컴포넌트**의 경우에는 React가 개입하지 않고 DOM을 통해 값이 저장되고 관리되기 때문에 바닐라(React와 같은 라이브러리가 더해지지 않은 순수한 JavaScript)에서 사용되는 방식은 모두 비제어이기도 합니다.

### 2️⃣ 
사실 `<AddRestaurantModal>` 은 완전한 **비제어 컴포넌트** 입니다. 사실 사용하신 방식도 React에서 주로 사용하는 방식이 아닌 순수 JavaScript에서의 방식인지라 헷갈리실 수 있겠습니다만, 가능한 한 설명해 보겠습니다.

1. `ref` 를 사용하지 않는다고 제어 컴포넌트인 것은 아닙니다.

**중요한 것은 폼 안의 인풋 요소들이 React의 데이터 흐름에 직접적으로 해당되고 있는지입니다. React의 데이터 흐름 바깥에 있다면 비제어 컴포넌트입니다.**

`ref`를 사용하는 것은 React에서 기본적으로 상태를 관리하고 업데이트하는 방식으로 진행됨에도 **불구하고**, 특정 컴포넌트나 영역을 상태로 관리하지 않고 **직접 DOM 요소를 참조하고 조작해야 할 일이 생길 경우** 사용됩니다. **React의 데이터 흐름에 영향을 주지 않는 것** 도 특징입니다. React에서는 특별한 상황이 아닐 경우에는 상태를 이용해 데이터의 흐름을 관리할 것을 추천하고 있지만, 몇몇 한정적인 상황에서는 `ref`를 추천하기도 하는데, 대표적인 예시로 아래의 경우가 있습니다.
- 컴포넌트의 DOM 요소에 직접 접근해 해당 요소에 **포커싱**을 줘야 하는 경우

왜 `ref` 가 언급되는 경우가 많냐면, 일반적으로는 직접 DOM 요소를 참조하고 조작해야 하는 상황이 있다면 React에서는 `ref`를 이용해 그러한 동작을 하는 것이 권장되기 때문입니다.

`FormData` Web API를 사용하신 경우에는 React의 데이터 흐름 내에 있지 않으며 직접 여러 인풋 DOM 요소들에 **직접 접근** 하여 값들을 가져옵니다. 따라서 사용하신 방법은 비제어 컴포넌트이며, 그 중에서도 바닐라에서 사용하는 전통적인 방식입니다.

물론 의문이 드실 수도 있다고 생각합니다 -- 음식점이 추가될 때 분명 상태를 업데이트하고 있거든요. 그래서 질문을 드릴 때 정확하게 **`<AddRestaurantModal>` 의 인풋과 폼** 을 찍었었던 겁니다. 개발자분들마다 의견이 많이 갈리기도 하거든요 😓 

음식점이 추가될 때에는 크게 아래의 프로세스가 순서대로 진행되는 것으로 보여요.
1️⃣ 사용자가 폼에 여러 데이터들을 입력해요.
2️⃣ 사용자가 입력 완료를 하고, 부모 컴포넌트의 함수를 호출하며, 부모 컴포넌트는 먼저 자식 컴포넌트의 폼에 FormData API를 이용해 직접 접근하여 폼의 정보들을 가져오게 됩니다.
3️⃣ 데이터들을 부모 컴포넌트 자신의 state에 반영합니다.

여기서 1️⃣ , 2️⃣ 까지가 폼 입력 및 자신의 데이터를 원하는 곳에 전송하는 파트였는데, 여기에서 React의 개입이 진행되지 않았어요. 그래서 **비제어 컴포넌트** 라고 제가 주장해 보았습니다.

## 현재 플로우(비제어)
![image](https://github.com/user-attachments/assets/c31f86b7-5477-4705-9cf0-7ca9005b69ba)

## 제어 컴포넌트로 관리된다면
![image](https://github.com/user-attachments/assets/abb8018e-fc86-4220-98c4-adefc9739ec1)

2024-11-11 13:44 UTC, wzrabbit commented on src/components/Aside/AddRestaurantModal.jsx
내용이 복잡하고 폼을 관리하는 방법도 너무 많다보니 (특히 React에서의 방법과 바닐라에서 주로 사용하는 방법들도 섞여있다보니) 아마 복잡하실 것이라 생각합니다.

제어 컴포넌트로 관리되고 있는 인풋이라면 대개 아래의 특징을 지닙니다. 기본적인 베이스이므로 variation이 있을 수는 있지만, 핵심적인 부분은 **React에 의해 제어되고 있는지의 여부**입니다.
- `value`의 값은 React의 `state`와 연결됩니다.
- `onChange`에는 `state`를 업데이트하는 함수가 있거나 비슷한 로직을 수행하는 함수가 부착되어 있습니다.
- 이 특징으로 인해, value의 값이 변경될 **때마다** **상태가 업데이트되고**, **리렌더링이 일어**납니다.

아래는 React에 의해 제어되는 인풋의 예입니다.
```jsx
const [value, setValue] = useState('');

return (
  ...
  <input value={value} onChange={(event) => setValue(event.target.value)} />
  ...
);
```

준수님이 구현하신 방법과 차이점이 느껴지시나요?

2024-11-11 13:44 UTC, wzrabbit commented on src/App.jsx
> +    setRestaurantList([...restaurantList, newRestaurant]);
최종 코멘트에 달겠습니다!

2024-11-11 13:44 UTC, wzrabbit commented on src/App.jsx
> +            onFormSubmit={(event) => toggleModal("add", false, null, event)}
충분히 고민해 보시길 바래요 💪🏻 5단계에서도 여전히 궁금하신 점이 있다면 저도 해볼만한 조언을 드릴 수 있도록 해 보겠습니다

2024-11-11 13:44 UTC, wzrabbit commented on src/App.jsx
> +    setIsModalOpen((prev) => ({ ...prev, [modalType]: isOpen }));
두 분의 설명은 모두 정확하다고 생각해요. 저렇게 이전 상태를 들고 상태를 업데이트하는 방법은 functional update라고 보통 부르는데, **확정적으로 바로 직전의 상태를 얻어야 할 때** 사용할 수 있어요.

비슷해 보이는 두 코드를 올려볼게요.

## 1️⃣ 
```tsx
import { useState } from 'react';

const Counter = () => {
  const [count, setCount] = useState(0);

  const handleClick = () => {
    setCount(count + 1); // setCount(0 + 1);
    setCount(count + 1); // setCount(0 + 1);
    setCount(count + 1); // setCount(0 + 1);
  };

  return (
    <>
      <div>{`Count is: ${count}`}</div>
      <button onClick={handleClick}>Increment</button>
    </>
  );
};
```

## 2️⃣ 
```tsx
import { useState } from 'react';

const Counter = () => {
  const [count, setCount] = useState(0);

  const handleClick = () => {
    setCount((prev) => prev + 1); // setCount(0 + 1);
    setCount((prev) => prev + 1); // setCount(1 + 1);
    setCount((prev) => prev + 1); // setCount(2 + 1);
  };

  return (
    <>
      <div>{`Count is: ${count}`}</div>
      <button onClick={handleClick}>Increment</button>
    </>
  );
};
```

단순히 기존의 state를 사용하는 1️⃣ 번 예시는 세 번의 `setCount`에도 불구하고 한 번만 반영되지만, 2️⃣ 번 예시에서는 세 번의 `setCount` 모두 **바로 직전의** 상태값을 이용해 반영하므로 세 번 모두 반영되어 정상적인 업데이트가 진행되는 것입니다. 이게 바로 사용처이자 차이점입니다.

## 여기서부터는 좀 깊을 수 있어요. 지금은 그런 게 있구나 정도로 생각해 봅시다

더 엄밀하게 이 원리를 파헤쳐보죠. 왜 두 번째 예시만 제대로 반영되는지.

두 컴포넌트는 모두 클릭되면 수가 늘어나는 카운터 컴포넌트에요. 둘 다 클릭되면 카운트가 **3**씩 증가할 것으로 보이지만, 실제로는
- 1️⃣ 의 경우 **1**만 증가해요. (?!)
- 2️⃣ 의 경우 **3**이 증가해요.

왜 이런 일이 발생하냐면, `setState` 가 호출된다고 해서 바로 그 `state`가 변경되는 것은 **아니기** 때문입니다. 일반 변수랑은 좀 다른 형태입니다.

`state`를 새롭게 변경하면 React에 리렌더링을 요청하게 되고 그 결과 리렌더링이 진행되면서 `state`가 반영될 것입니다. 다만 **`state`를 새롭게 설정하면 리렌더링 전 현재 상황에 대해 React는 스냅샷을 찍게 되고, 세 개의 `setCount` 모무 `count`는 스냅샷에 찍힌 값인 **0**이 반영됩니다.

그래서 첫 번째 예시에서는 React는 값을 `1`로 변경시킬 준비를 세 번이나 하는 거에요. 물론 몇 번이 일어나든 `1`이 되겠죠.

`setCount`가 세 번 호출되었으므로 세 번 리렌더링되는 것이 아니냐라고도 생각하실 수 있지만, React는 배칭(batching)이란 것을 사용합니다. **단기간에 일어나는 여러 상태변화는 하나로 묶어서 처리됩니다.** 그렇기 때문에 리렌더링은 **1**회이며, 스냅샷을 각 `setCount`마다 새로 찍어서 반영시키지는 않는 거에요.

2024-11-11 13:44 UTC, wzrabbit commented on src/components/Aside/AddRestaurantModal.jsx
> +                            <option key={category.id} value={category.name}>{category.name}</option>
`index` 를 사용하는 안티 패턴을 이용해 메인테이너님이 예를 들어주셨나 보군요? 사실 `index` 가 꼭 아니어도 React가 키 값을 제대로 활용하지 못해 잘못 작동하거나 성능이 안 좋아지는 상황은 여럿일 수 있어요.

여쭤보고 싶었던 점은 `category.id` 는 과연 이러한 부작용 없이 React가 문제 없이 사용할 수 있는 키 값이 될 수 있는가? 였습니다. 그리고 `category.id`는 현재 상황에서는 **키 값이 겹칠 일이 전혀 없으므로** React가 혼동 없이 각 항목을 식별할 수 있고, (그럴 일은 없지만) 리스트 내부의 **순서가 바뀌더라도 각 키 값이 대응되는 항목을 일관성 있게 가리키고** 있으므로 적절한 상황이라고 생각되네요 🏁

2024-11-12 14:00 UTC, gogo1414 commented on src/data/Restaurant.js
> +}
자바스크립트에도 class가 존재하는걸 이제 알았네요...

2024-11-12 14:09 UTC, gogo1414 commented
> ref 를 사용하지 않는다고 제어 컴포넌트인 것은 아닙니다.
> 중요한 것은 폼 안의 인풋 요소들이 React의 데이터 흐름에 직접적으로 해당되고 있는지입니다. React의 데이터 흐름 바깥에 있다면 비제어 컴포넌트입니다.

제가 숲이 아닌 나무를 바라보았네요 더 큰 개념으로 보면 데이터 흐름이 존재한다는 것을 깨달았을텐데 요술토끼님 덕분에 지식이 하나 늘어갑니다..!

>물론 의문이 드실 수도 있다고 생각합니다 -- 음식점이 추가될 때 분명 상태를 업데이트하고 있거든요. 그래서 질문을 드릴 때 정확하게 <AddRestaurantModal> 의 인풋과 폼 을 찍었었던 겁니다. 개발자분들마다 의견이 많이 갈리기도 하거든요 😓
>
>음식점이 추가될 때에는 크게 아래의 프로세스가 순서대로 진행되는 것으로 보여요.
>1️⃣ 사용자가 폼에 여러 데이터들을 입력해요.
>2️⃣ 사용자가 입력 완료를 하고, 부모 컴포넌트의 함수를 호출하며, 부모 컴포넌트는 먼저 자식 컴포넌트의 폼에 FormData API를 이용해 직접 접근하여 폼의 정보들을 가져오게 됩니다.
>3️⃣ 데이터들을 부모 컴포넌트 자신의 state에 반영합니다.
>
>여기서 1️⃣ , 2️⃣ 까지가 폼 입력 및 자신의 데이터를 원하는 곳에 전송하는 파트였는데, 여기에서 React의 개입이 진행되지 않았어요. 그래서 비제어 컴포넌트 라고 제가 주장해 보았습니다.

데이터의 흐름이 자주 변경되는 복잡한 컴포넌트가 존재할 경우 제어, 비제어를 구분하는게 더 쉽지 않겠네요! 확실히 개발자분들이 의견이 갈릴만한 내용인 것 같습니다!

2024-11-12 14:17 UTC, merged