[5단계 미션] 박예은 미션 제출합니다
cho-log/self-paced-react pull request #34
Opened 2024-11-11 12:10 UTC by ye6194

2024-11-12 14:24 UTC, gogo1414 approved these changes
> 예전에 자바스크립트로 api를 호출하고 사용해본 적이 있어서 이번에도 같은 방식으로 코드를 작성 후 response를 출력해보니 제가 원하는 데이터가 없었습니다. 알고보니 예전에는 axios를 이용해서 response가 자바스크립트 객체로 자동 변환됐지만, 이번 미션에서는 axios를 쓰지 않고 fetch를 사용했기 때문에 json()을 호출해 직접 변환해야 했던 것이었습니다.
.json 파일은 많이 봤지만 json이 뭔지 잘 몰랐었는데, 이번 기회에 json이 무엇인지 확실하게 알게 되었습니다.

과거에 사용했던 방식에서 발생한 문제점을 정확하게 파악하시고 해결하시는 점이 너무 좋네요! 
json은 엄청 다양한 곳에서 사용되는거 같아요 저도 백엔드 개발을 할 때 json 형식으로 매핑이 필요한 곳이 존재했었는데, 그때 json 형식에 대해 배우게 된 것 같네요ㅎㅎ

5단계 미션도 고생하셨습니다👍👍

2024-11-12 14:24 UTC, gogo1414 commented on src/App.jsx
> +  }, [restaurantList]);
> 또한, async가 붙은 함수는 promise를 반환한다는 것과 then이 promise가 resolve(해결)되었을 때 호출된다는 것도 알게 되었습니다.

해당 내용을 정확하게 알고 사용하신 점이 인상 깊네요..! 저는 코드를 구성할 때 then의 존재에 대해 전혀 몰랐는데 하나 알고갑니다!

2024-11-12 14:24 UTC, gogo1414 commented on src/api/restaurantAPI.js
api 요청을 따로 분리하셔서 관리하시는 점 멋지십니다👍👍

2024-11-13 02:27 UTC, ye6194 commented on src/api/restaurantAPI.js
나중에는 API 코드 파일 분리뿐만 아니라 API를 커스텀 훅으로 만들어서 관리하는 것도 생각하고 있습니다😊

2024-11-14 01:29 UTC, wzrabbit requested changes
@ye6194 👋🏻 

오늘은 수능이군요. 잘 쉬고 계신가요? 그랬으면 좋겠네요... 😢

## 리뷰 🗒️ 

이번 미션에는 가짜 서버를 실행을 위해 `http-server` 를 세팅하는 과정이 별도로 있었군요? 지금까지 더미 데이터만을 사용했는데 이제 좀 더 애플리케이션이 된 느낌이 드네요. 세팅 군더더기 없이 잘하셨어요, 잘 작동합니다 👍🏻 

API 로직과 같이 여러 곳에 사용될 수 있고, 복잡해질 우려가 큰 로직도 잘 분리하셨어요, 디렉토리 및 파일명도 내부 코드를 보지 않고도 무슨 역할을 하는 것인지 이해하기 수월했어요.

`useEffect` 사용에 대해서는 현재 코드에서 아쉽게도 무한루프가 발생하고 있는 것 같아요 😢 코멘트에 하고 싶은 이야기를 적어드렸으니 무한루프는 꼭 해결해 보셨으면 좋겠어요.

`useEffect`에 대해서는 이 녀석의 기능을 중점으로 질문을 드렸어요. 어떨 때 사용하면 좋은지, 원리는 어떠한지 등도 여쭤볼 수 있었습니다만 도통 파악하기 어려운 녀석이라, 그러한 질문은 드리지 않기로 했습니다. 그 대신 공식 문서에 이러한 내용들이 잘 설명되어 있으니 공식 문서를 확인해 보실 것을 추천드려요.
- https://ko.react.dev/learn/synchronizing-with-effects

벌써 초록 스터디의 마지막 단계의 미션이네요. 마무리도 잘 해 보자고요 👍🏻 
그럼, 예은님의 의견 기다리고 있겠습니다.

2024-11-14 01:29 UTC, wzrabbit commented on src/App.jsx
> +  }, [restaurantList]);
앗. 이 코드, 자칫하면 무한루프를 돌겠는데요...? 🤔 

1. 의존성 배열에 무엇이 있는지
2. `useEffect` 내에서는 무엇이 업데이트되는 지
 
를 꼼꼼하게 다시 검토해 보셨으면 좋겠습니다. 이곳에서의 무한 루프는 곧 무한 렌더링을 의미하고, 무한 렌더링은 곧 불필요한 성능 악화로 이어지므로 발생하지 않도록 철저하게 관리하셔야겠습니다.

무한 루프를 해결하셨다면, 왜 무한 루프가 발생했었는 지 저에게도 알려주시면 좋겠어요! 😊

- [React Developer tools](https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)를 사용하면 컴포넌트가 렌더링되는 경우 해당 컴포넌트에 윤곽선이 표시되도록 해 렌더링 여부를 알 수 있도록 해 주는 기능이 있습니다. 윤곽선이 계속해서 사라지지 않으면 무한 렌더링을 의심해 볼 수 있겠죠.
- 이 `useEffect` 내부에 `console.log()` 을 사용하시는 방법으로도 육안으로 확인하실 수 있을 것입니다.

2024-11-14 01:29 UTC, wzrabbit commented on src/api/restaurantAPI.js
로직 분리 정말 잘 하셨어요! 이렇게 복잡할 수도 있는, 그리고 여러 곳에서 광범위하게 사용될 수도 있는 API 로직들은 분리했을 때 이점이 많을 거라고 생각해요.

2024-11-14 01:29 UTC, wzrabbit commented on src/api/restaurantAPI.js
> +  const data = await response.json();
axios가 그리우신가요? 😊

2024-11-14 01:29 UTC, wzrabbit commented on src/App.jsx
## 인터뷰 🎤 

1. useEffect는 어떤 일을 수행하나요? (자세한 원리를 여쭤보는 것이 아니라, useEffect가 하는 기능, 행동 그 자체를 여쭤보는 것입니다. 젓가락은 음식을 집는 데 사용하고, 마우스는 마우스 커서를 움직이는 데 사용하죠.)
2. useEffect의 dependency array라는 것은 무엇이고, 어떤 기능을 담당하나요?
3. useEffect 내부의 코드는 언제 실행되나요?
4. 아래 두 코드의 차이점은 무엇일까요?

```jsx
useEffect(() => {
  console.log('effect!');
}, []);
```

```jsx
useEffect(() => {
  console.log('effect!');
});
```

2024-11-14 10:58 UTC, ye6194 commented on src/api/restaurantAPI.js
> +  const data = await response.json();
네...🥹

2024-11-14 11:50 UTC, ye6194 commented on src/App.jsx
### 🗣️ 답변

1. useEffect는 부수 효과를 처리합니다!

2. 의존성 배열은 useEffect가 언제 실행될지를 결정합니다.
   - 의존성 배열 안에 있는 값이 바뀔 때마다 useEffect 내부의 코드가 다시 실행됩니다. 
   - 의존성 배열을 비워두면 컴포넌트가 처음 렌더링(마운트)될 때만 실행됩니다.
 
3. 2번에서 답한 것처럼, 컴포넌트가 마운트될 때 한번 실행되고, 의존성 배열 안의 값이 바뀔 때마다 실행됩니다.

4. 첫번째 코드는 컴포넌트가 마운트될 때 한번만 실행되고, 두 번재 코드는 컴포넌트가 렌더링될 때마다 실행된다는 차이점이 있습니다.

2024-11-14 12:40 UTC, ye6194 commented on src/App.jsx
> +  }, [restaurantList]);
코드를 실행했을 때 아무 문제 없이 잘 작동하는 것처럼 보여서 무한루프가 발생할줄은 몰랐는데 useEffect 내부에 콘솔 로그 찍어보니까 난리가 났네요😢

1. 의존성 배열에 `restaurantList`를 둔 의도는,
 우선 처음 렌더링될 때 useEffect를 실행하고, 헤더의 버튼을 눌러 레스토랑을 추가하는 등의 행동을 해서 `restaurantList`가 바뀌었을 때 useEffect가 다시 실행되게 하려고 했던 것이었습니다. 

2. 처음 렌더링될 때 useEffect 내에서 `setRestaurantList` 실행 -> `restaurantList` 변화 -> 의존성 배열에 `restaurantList`가 있어서 다시 useEffect 내에서 `setRestaurantList` 실행 -> 무한반복
이렇게 됐던 거네요. 이제보니 무한루프가 실행되는게 당연한 코드인데 미션을 구현할 때는 왜 모르고 넘어갔는지 모르겠네요😂

2024-11-14 12:45 UTC, ye6194 commented
@wzrabbit 
안녕하세요 의천님! 
벌써 수능이네요. 수능이지만 쉬진 못하고 평소랑 똑같아요...
고3과 n수생들한테 방해되지 않게 오늘은 휴강했어야 했는데 참(?)...

무한루프가 발생한걸 미션 구현할 때 바로 알아차리지 못했던 건 아쉽지만 그래도 새로운 크롬 확장 프로그램 알아갑니다ㅎㅎ
그리고 인터뷰를 통해 알던 것을 복습하기도 하고 헷갈렸던 것을 다시 찾아보며 확실하게 알게 되었어요.

이번주도 코드 리뷰 하시느라 수고하셨습니다🙇‍♀️

2024-11-15 16:40 UTC, wzrabbit reviewed
렌더링과 상태에 대한 고민을 많이 하셨으리라 생각됩니다.
그냥 비동기 로직을 구현하는 것도 어려운데 React 안에서 돌아가는 비동기 로직은 더 어려울 수도 있다고 생각하고 있어요.

저도 답변을 달 때 어떻게 해 보면 좋을 지 고민해 보았고, 100% 완벽한 답이 아닌 개발자로써 제가 생각하는 의견을 적어보았습니다.

아이디어를 얻어가실 수 있으면 그걸로 만족하고요, 제 방법을 곧이곧대로 따라하실 필요는 없습니다. 다른 좋은 방법이 떠오르신다면 그 방법을 시도해보세요. 저도 피드백을 다시 드릴 수 있도록 해 볼게요!

2024-11-15 16:40 UTC, wzrabbit commented on src/App.jsx
<img src="https://user-images.githubusercontent.com/87642422/233828081-bec1bb8b-7c29-4fac-8c67-0c84bb814ee2.png" width="35px" />

2024-11-15 16:40 UTC, wzrabbit commented on src/App.jsx
> +  }, [restaurantList]);
아하, 그러니까 레스토랑이 추가될 때마다 **서버에서의 데이터와 완전히 동기화된** 리스트를 항상 보여주도록 기능을 구현하고 싶으신 것이군요. 그런데 `restaurantList`가 변경될 때마다 다시 `fetch` 해오는 `useEffect` 훅을 사용하자니 `fetch` 한 경우에도 `restaurantList`가 변경되는 것으로 겹치는 경우가 있다 보니 무한 루프가 발생할 여지가 있는 것이고요.

원하시는 대로 가능한 한 **최신화된** 데이터가 반영되도록 구현해 본다면, 그리고 간단하게 구현해 본다면, 저는 아래의 방법을 사용해 볼 것 같아요.

## 레스토랑을 추가할 때마다 서버로부터 최신 레스트랑 목록을 받아온다음, 업데이트한다면?
1. 초기 마운팅 이후 레스토랑 목록을 서버로부터 불러올 수 있도록, `useEffect` 훅과 `fetch` 로직을 작성합니다. 의존성 배열은 `[]`로 둡니다.
2. 새로운 레스토랑이 추가되어야 하면, 먼저 서버에 요청을 해 최신 레스토랑 목록을 가져옵니다.
3. 최신 레스토랑에 새로운 레스토랑을 추가시킨 배열을 만듭니다.
4. [3] 에서 만든 배열을 새로운 상태로 업데이트합니다.
5. [3] 에서 만든 배열을 `POST` 요청을 통해 서버로 전송합니다.

이렇게 레스토랑이 추가될 때마다 모든 레스토랑 목록을 불러오는 방법은 서버에 부담을 더할 수 있는 방법이 될 수 있겠지만, 이 서비스가 작은 규모의 서비스인 것을 생각하면 괜찮은 방법이 될 수 있다고 생각됩니다.

또한 최신화된 레스토랑의 목록을 불러와야 할 경우 불러올 때까지 업데이트를 미뤄야 하므로 시간이 더 걸릴 수 있으며, 사용자가 딜레이를 느낄 수도 있는 방법이 될 수 있겠지만, 역시나 레스토랑을 추가하는 작업은 사용자가 매우 빈번하게 (초당 수 회) 추가하지 않을 것이 예상되므로 딜레이는 큰 문제는 되지 않을 것이라고 생각됩니다.

<hr>

이것보다도 약간 더 최적화해볼 수 있어 보이지만, 일단은 "서버와 소통하는 기초적인 어플리케이션 만들기" 가 본 미션의 목표이므로 주제에 벗어나는 것 같아보이는군요.

2024-11-15 16:40 UTC, wzrabbit commented on src/App.jsx
> +  }, [restaurantList]);
> 근데 의존성 배열을 비우고 레스토랑 추가 버튼을 눌렀을 때 새로고침하는 코드를 추가해서 무한루프를 해결했는데,
새로고침 하는게 좋은 해결 방법인게 맞을까요?

추천드리고 싶지 않습니다. 새로고침을 하게 되면 너무 많은 것을 잃게 될 것이라 생각합니다.

- **SPA의 대부분의 장점을 잃습니다.** SPA는 처음 불러올 때에는 여러 페이지에 해당하는 리소스를 모두 가져오므로 초기 로딩 속도는 느리지만 이후에는 사용자가 페이지를 전환하는 등 여러 상호작용을 해도 이미 로드해두었던 리소스를 사용하고, 변경되는 부분만 변경되도록 하는 장점이 있으므로 성능 및 사용자 경험 면에서 상당히 좋습니다. 그러나 새로고침을 사용하면 **이 모든 리소스들을 다시 로드해야 합니다**.
- 대다수의 사용자는 레스토랑을 하나 추가했다고 웹페이지가 새로고침될 것이라는 것을 예상하기 어렵습니다. 새로고침을 어쩔 수 없이 해야 하는 상황이라면 보통 사용자가 새로고침 버튼이라는 것을 알고 누르게 하거나, 사용자에게 새로고침과 관련해 양해를 구하는 것이 UX를 덜 저하시키는 방법이라고 생각합니다.
- 새롭게 웹사이트가 로드되므로 깜박임(Flickering) 현상이 발생할 수 있습니다. 깜박이는 현상은 사용자가 가장 싫어하는 현상 중 하나입니다.
- 레스토랑을 추가하는 기능은 사용자가 사이트 내에서 빈번하게 사용할 수 있는 기능입니다.

레스토랑을 추가하는 로직은 웹사이트 전체를 새로고침해야 할 정도로 큰 로직이라고 생각되지도 않습니다. 따라서 새로고침을 하는 방법은 추천드리고 싶지 않습니다.

SPA를 왜 사용하는지, 어떤 장점을 얻어가고자 하는지를 고민해 보시면 도움이 되실거라 생각합니다.

2024-11-15 16:40 UTC, wzrabbit commented on src/App.jsx
> +  }, [restaurantList]);
저도 제 개인 프로젝트에 새로고침을 진행하는 로직을 넣은 적이 있습니다. 현재 여러 컴포넌트들을 한꺼번에 최신화시킬 수 있는 기능을 만들기 어려운 상황에 처해 있었고, **데이터 초기화** 기능을 담당하는 만큼 사용자가 자주는 사용하지 않을 기능이라 생각해, **새로고침 경고 문구** 를 같이 넣으며 기능을 구현했습니다.

![image](https://github.com/user-attachments/assets/047d69df-f189-4780-a141-d735eed4491d)

그래도 더 개선되어야 한다고 생각하고 있어요. 지금도 새로고침 없이 데이터 초기화를 구현할 방법을 모색하고 있습니다. ✏️

2024-11-17 06:09 UTC, ye6194 commented
새로고침을 하면 왠지 안 좋은 영향이 있을 것 같긴 했지만 대수롭지 않을 거라고 생각했는데 생각보다 더 안 좋은 방법이었네요...!
SPA라는 개념을 알게 새롭게 알게 되었고, 새로고침을 쓰지 않는 방법으로 바꿨어요.

<br/>

> 1. 초기 마운팅 이후 레스토랑 목록을 서버로부터 불러올 수 있도록, useEffect 훅과 fetch 로직을 작성합니다. 의존성 배열은 []로 둡니다.
> 2. 새로운 레스토랑이 추가되어야 하면, 먼저 서버에 요청을 해 최신 레스토랑 목록을 가져옵니다.
> 3. 최신 레스토랑에 새로운 레스토랑을 추가시킨 배열을 만듭니다.
> 4. [3] 에서 만든 배열을 새로운 상태로 업데이트합니다.
> 5. [3] 에서 만든 배열을 POST 요청을 통해 서버로 전송합니다.

저는 이걸 보고 3에서 만든 배열을 addRestaurant에 인자에 넣으라는 뜻으로 이해했는데 제가 이해한 게 맞나요??
addRestaurant에 객체 하나가 아닌 객체 배열을 넣으면 작동이 안될 것 같았지만 그래도 일단 해봤는데 제대로 작동하지 않네요😢

그래서 저는 AddRestaurant.jsx의 addRestaurant를 호출할 때 인자로 newRestaurant를 넣고, 상위 컴포넌트(App)에 상태를 업데이트해야 함을 알렸어요. 그 후 최종적으로 App에서 상태를 업데이트하는 방식으로 로직을 짜보았어요.

2024-11-17 12:12 UTC, wzrabbit commented
> addRestaurant에 객체 하나가 아닌 객체 배열을 넣으면 작동이 안될 것 같았지만 그래도 일단 해봤는데 제대로 작동하지 않네요😢

아하, 다시 확인해보니 POST 요청을 날릴 때에는 레스토랑 하나를 인자로 받도록 구현되어 있군요. 이 부분은 제가 제대로 인지하지 못했네요, 죄송합니다. 😓 이 부분은 예은님이 사용하시던 대로 요청해주시면 됩니다.

그 외에도, 지금까지 구현해 주신 방향을 기준으로 문제를 해결하실 수 있도록 피드백해보겠습니다.

## 1️⃣ 의도
코드를 살펴보니 **`<AddRestaurantModal>`**가 직접 서버로 새로운 레스토랑을 추가할 것을 요청하도록 구현해 주신 것 같아요. 그 경우라면 실질적인 추가는 `<App>`이 담당하지 않고 `<AddRestaurantModal>`로부터 데이터만 업데이트할 것을 요청받아 업데이트를 진행하겠군요?

API 로직은 이미 이전에 잘 구현해두셨고, 그러면 `<App>`이 무사히 새롭게 반영된 레스토랑 목록을 보여주도록 구현해 보아야겠네요?

## 2️⃣ 문제점 해결해보기 🔨 

1️⃣ 레스토랑을 추가할 때마다 **새로고침되는 현상**을 해결해 봅시다

`location.reload()` 를 제거하신 것은 확인했습니다! 다만 이번에는 모달에 있는 **레스토랑 추가 버튼**이 새로고침을 유발하고 있었던 것으로 보입니다. 어쩌면 이로 인해 최신 상태가 잘 반영되는 것"처럼" 보였을 수도 있을 것 같아요.

`<button>` 의 경우 `type`을 지정하지 않으면 기본적으로 타입은 `submit`이 됩니다. 이러한 타입의 버튼은 폼을 제출하도록 동작하기 때문에 클릭할 경우 브라우저가 새로고침되는 현상이 발생할 수 있습니다. 이는 버튼의 **기본 동작**입니다.

우리가 구현하고자 하는 기능은 폼을 제출하는 것이 맞지만, 다른 페이지로 리다이렉트시키는 식으로 제출하는 것이 아닌 브라우저를 새로고침하지 않으면서 `fetch` 를 이용해 서버와 소통하도록 구현하는 것이 목표이므로 이러한 **기본 동작** 은 방해가 될 수 있고 의도에도 어긋나겠죠?

따라서 기본 동작을 발생시키지 않도록 개선하시는 것이 필요해 보입니다. 크게 두 가지 방법으로

1. `<button>`의 `type`을 `"button"`으로 명시해 줍니다. 폼 제출용 버튼이 아닌 일반 버튼으로 사용하고자 할 때 사용할 수 있습니다. 이렇게 하더라도 추가해야 되는 레스토랑의 정보를 불러올 수 있으므로 지장이 없을 것입니다.
2. `<button>` 의 `type`을 바꾸지 않고 `submit` 이벤트에 대한 처리를 하도록 구현하셔도 문제를 해결하실 수 있습니다. 이 경우에는 해당 버튼에 `onClick` 이벤트 프로퍼티를 달기보다는 `<button>` 이 있는 `<form>`에 `onSubmit` 이벤트 프로퍼티를 다는 것이 적절한 사용법이 될 수 있을 것 같습니다. 또한, 기본 동작을 막아야 하므로 `event.preventDefault()` 를 사용해 주셔야 할 것입니다.

둘 중 적절하다고 생각하시는 방법을 선택해 주시면 될 것 같아요!

2️⃣ 레스토랑이 추가될 때마다 최신 레스토랑 목록을 가져오도록 해 봅시다

[1️⃣] 을 무사히 완료하셨다면 새로고침 현상은 이제 발생하지 않을 거에요! 하지만 여전히 레스토랑을 추가했을 때 최신 레스토랑 목록이 보이지는 않을 거에요.

```jsx
const updateRestaurantList = (newRestaurant) =>
    setRestaurantList((prevList) => [...prevList, newRestaurant]);
```

현재 위와 같은 로직을 작성해주셨지만, 이는 어디까지나 **브라우저 안에서의 상태 기준** 에서 최신의 상태를 가져오는 것이기 때문에, 다른 사용자들이 레스토랑을 추가해 서버의 정보가 변경된 경우에는 이를 알 수 없을 거에요. 이는 외부 영역이기 때문에 어쩔 수 없는 부분이에요. 따라서 우리는 직접 `fetch` 를 사용해 다시 한 번 서버로부터 최신화된 정보를 받아오고, 그 정보를 레스토랑 목록에 해당하는 상태에 업데이트해주도록 구현할 수 있을 거에요.

이 경우 `<App>`에서는 레스토랑을 새롭게 추가하는 로직보다는 하위 컴포넌트로부터 알림만을 받고 정보를 갱신해주는 작업에 더 가까워요. 따라서 `newRestaurant` 인자 또한 필요하지 않을 것이라 예상해 봅니다.

그림으로도 현재 구현하신 로직과 요구사항을 정리해 보았습니다. 화이팅입니다!

![image](https://github.com/user-attachments/assets/253a86aa-4944-4e1c-b877-c0a360337bb7)

2024-11-18 13:31 UTC, wzrabbit approved these changes
드디어! 성공하셨군요!
테스트해봤는데 새로고침도 없고 로직도 깔끔하게 모두 잘 작동합니다.

긴 기간동안 저와 코멘트 주고받으시느라 수고 많으셨어요. 이로써 초록 스터디에서의 미션들은 모두 끝이 났습니다.

뒤에 메인테이너님이 어떤 고되고 빡센 미션을 주실지는 모르겠지만... 😭 
잘 해결하실 수 있을 거라고 생각합니다!

그동안 수고 많으셨습니다 👍🏻 

<img src="https://github.com/user-attachments/assets/e443847c-d158-4740-9fac-7d6640701520" width="65px" />

2024-11-18 13:31 UTC, wzrabbit commented on src/App.jsx
> +  };
👍🏻

2024-11-18 13:32 UTC, merged