[5단계미션] 송혜정 미션 제출합니다.
cho-log/self-paced-react pull request #35
Opened 2024-11-12 14:44 UTC by Songhyejeong

안녕하세요 리뷰어님 !
이번주차는 드디어 마지막 미션인 API를 연결해보는 과정을 진행해보았어요
점심 뭐먹지 프로그램을 완성할 수 있어서 좋았습니다!

이번 미션에서 중요했던 것이 useEffect를 사용하는 것이었는데 처음에는 restaurant 데이터가 바뀔 때마다 함수를 실행하게 하고 싶었는데 함수 안에 restaurant를 변경하는 setter 함수가 있어서 POST 요청 안에 GET요청을 넣었습니다..
사실 이번 미션은 급하게 구현 하느라 코드를 수정하고 싶은 부분을 하지 못해 아쉬웠습니다. 계속해서 리팩터링 진행하면서 수정해보겠습니다!

### 궁금한 점
준수님 코드리뷰 하다가 궁금해 진건데 API 요청은 따로 hook으로 만들어서 관리하는 것이 좋을까요? 리뷰어님은 평소 API 요청 코드를 어떻게 관리 하시는지 궁금하네요! 

### 구현 기능
- API 연결 
- 레스토랑 리스트를 요청하는 기능
- 레스토랑을 추가하는 기능

### 파일 구조
<img width="742" alt="Screenshot 2024-11-12 at 10 31 54 PM" src="https://github.com/user-attachments/assets/b267cfa0-04db-4f28-a9f0-25275a429b2e">

### 이미지
<img width="1710" alt="Screenshot 2024-11-12 at 11 24 59 PM" src="https://github.com/user-attachments/assets/d470d48b-1d4c-43f8-bbba-d1265e716046">

2024-11-13 01:51 UTC, ye6194 commented on db.json
> +      "name": "ㅇ라머",
이 부분은 지우셔도 될 것 같습니다!

2024-11-13 01:51 UTC, ye6194 commented on src/App.jsx
> +  }, []);
혜정님은 api 안에서 setRestaurantsList를 호출하셔서 의존성 배열을 비워두셨네요! 저는 api 밖에서 setRestaurantsList을 호출해서 의존성 배열에 restaurantList가 있답니다.

2024-11-13 01:51 UTC, ye6194 commented on src/App.jsx
> +import { useEffect } from 'react';
```suggestion
import { useState, useEffect } from 'react';
```
한줄로 줄여쓰는게 좋을 것 같아용

2024-11-13 01:51 UTC, ye6194 commented on src/App.jsx
> +      setRestaurantsList([...jsonData]);
spread 👍

2024-11-13 02:02 UTC, ye6194 commented
안녕하세요 혜정님!
드디어 '점심 뭐 먹지' 미션이 끝났네요😊

> 준수님 코드리뷰 하다가 궁금해 진건데 API 요청은 따로 hook으로 만들어서 관리하는 것이 좋을까요? 리뷰어님은 평소 API 요청 코드를 어떻게 관리 하시는지 궁금하네요!

저는 API 요청을 따로 커스텀 훅으로 만들어서 관리하지는 않고 다른 파일에 분리만 해둬요. 이번 미션에서는 src/api 폴더에 restaurantAPI.js 파일을 만들어서 api 코드를 작성했어요.

<br/>

> restaurant 데이터가 바뀔 때마다 함수를 실행하게 하고 싶었는데 함수 안에 restaurant를 변경하는 setter 함수가 있어서 POST 요청 안에 GET요청을 넣었습니다..

이건 코드에 코멘트를 달고 나서 뒤늦게 보게된건데 원래 의존성 배열 안에 restaurant를 추가하시려고 하셨었네요😮 혜정님 말씀대로 나중에 리팩터링 해보시면 좋을 것 같아요!

마지막 미션까지 수고 많으셨습니다!

2024-11-13 13:33 UTC, Songhyejeong commented on src/App.jsx
> +  }, []);
오 api 밖에서 setter함수 호출하는 방법이,,, 왜 그런 생각을 못했을까요 알려주셔서 감사합니다!

2024-11-13 13:33 UTC, Songhyejeong commented on src/App.jsx
> +import { useEffect } from 'react';
넵!

2024-11-13 13:36 UTC, Songhyejeong commented on db.json
> +      "name": "ㅇ라머",
넵 ..! ㅋㅋㅋㅋㅋㅋㅋ

2024-11-15 08:54 UTC, Indigochi1d requested changes
혜정님 이번주 미션은 어떠셨나요? 이번주는 async/await 과 Promise 체이닝을 이용한 비동기 로직 처리에 관해서 배울 수 있는 미션이었어요! useEffect로 데이터를 fetching하는 방식까지 배울 수 있는 미션이었습니다! 원래 하셨던 방식대로 기능을 잘 수행하시고 함수도 읽기 쉬웠고 컴포넌트 내 비즈니스 로직의 책임이 명확했던 점이 좋았어요! 
혜정님의 코드를 보았을 때 `async/await`을 통해 비동기처리 로직을 쓰고 `useEffect Hooks`를 사용해 데이터를 비동기적으로 불러오는 것 에 능숙하다는 것이 보였습니다. `await`를 사용해서 처리하는 것에 대한 이해가 돋보였다고 생각해요. 저도 그랬었지만 관습적으로 `비동기처리로직 === async/await`로 생각해서 데이터를 서버와 CRUD 해야할 일이 생기면 손이 먼저 나가서 useEffect....를 적게 되고 그 안에 비동기로직(async/await)을 적어주시는 것 같아요. 뭔가 일반화(?)된 패턴이라고 생각합니다😄 

그래서 이번 리뷰에서는 `async/await `이전에 `Promise`가 무엇인지와 등장한 배경에 이어 `비동기로직`의 흐름에 대해서 조금 다뤄보려고 해요.
## Javascript에서의 비동기 로직의 필요성

## ❓ 서버와 통신할때 왜 비동기 로직이 필요할까요?
_**제일 중요한건 Javascript에서 메인 스레드의 블로킹 방지에요.**_

자바스크립트는 단일 스레드 기반으로 동작해요. 동기 방식으로 데이터를 페칭하면 네트워크 요청이 완료될 때까지 메인 스레드가 멈춰 있어, 다른 작업(예: UI 렌더링, 사용자 입력 처리)이 지연됩니다. 이는 아주 비효율적이고 이러면 애플리케이션이 제 기능을 하지 못해요. 그래서 비동기 처리를 통해 네트워크 요청이 진행되는 동안 메인 스레드는 다른 작업을 계속 처리할 수 있어요.

그래서 초기엔 비동기처리 로직을 콜백으로 작성해가며 작성해갔습니다. 불편한 구조죠..

## Promise란?
`Promise`는 콜백지옥을 피하기 위해 만들어졌어요. 콜백지옥이란 아래의 코드와 같습니다.
```javascript
fetchData(url1, (data1) => {
  fetchData(url2, (data2) => {
    fetchData(url3, (data3) => {
      console.log('All data loaded!');
    });
  });
});
```
JavaScript는 브라우저나 서버의 작업(파일 읽기, API 호출, 타이머 등) 결과를 기다리지 않고 다음 코드를 실행할 수 있는 비동기 프로그래밍을 제공해요. 초기에는 콜백 함수를 사용해 비동기 작업의 결과를 처리했습니다. 근데 누가봐도 저거 극단적으로 100개의 일을 비동기로 하라고 하면 콜백함수를 100번 써야돼요. 개발자는 죽어나죠...코드 가독성도 떨어질 뿐더러 디버깅, 유지보수에 최악이었습니다.

그래서 이 비동기 로직을 효과적으로 처리하기 위해 `ES6`에서 Promise를 도입합니다! Promise는 기존의 콜백지옥인 중첩구조를 `.then()` 을 통해 피할 수 있었어요. 
```javascript
fetchData(url1)
  .then(data1 => fetchData(url2))
  .then(data2 => fetchData(url3))
  .then(data3 => {
    console.log('All data loaded!');
  })
  .catch(error => {
    console.error('Error:', error);
  });
```
~짠!(뭔가 대단한 것을 소개하는 것처럼)~
중첩이 줄어들어 가독성이 좋아졌습니다. 또, `.then()`과 `.catch()`로 에러 처리를 명확히 관리할 수 있으며 `Promise.all()`과 `Promise.race()`를 사용해 병렬 처리도 간단히 구현할 수 있게 되었지만 여전히 동기식처럼 코드를 읽을 수 없었으며 체이닝이 너무 길어진다는 단점이 존재했습니다.
## async/await의 등장
#### 왜 async/await이 등장했는가?
`async/await`는 `Promise`를 더 자연스럽고 동기적인 방식으로 다룰 수 있도록 `ES2017 (ES8)`에서 도입되었습니다.
비동기작업이지만 동기적 코드를 작성할 수 있는 장점이 있었어요. 혜정님이 async/await으로 처리해주신 것도 아마 "편하고 읽기 쉬움"때문이었을 거라고 생각합니다. 코드 예제는 아래와 같아요.
```javascript
async function loadData() {
  try {
    const data1 = await fetchData(url1);
    const data2 = await fetchData(url2);
    const data3 = await fetchData(url3);
    console.log('All data loaded!');
  } catch (error) {
    console.error('Error:', error);
  }
}
```
하지만 여전히 `Promise`라는 개념을 잇는 것이기 때문에 `async`로 함수를 만들면 반드시 `Promise`객체를 반환해요. 그럼 여기서 **"Promise 객체란 뭡니까?"** 라고 하시면 
Promise 객체는 JavaScript에서 `비동기 작업의 성공 또는 실패 결과를 표현하는 객체`입니다! 이는 프로그래밍에서 비동기 작업이 완료되거나 실패했을 때 그 결과를 처리할 수 있도록 설계된 메커니즘이에요.관련 메서드와 정의는 [이 문서](https://poiemaweb.com/es6-promise)를 읽어보시면 더 좋을 것 같아요!!

다시 본론으로 돌아와 혜정님의 코드에서 async/await으로 비동기함수를 제어하고 있어서 좋았어요. 하지만 코드 리뷰에서 적어놨듯 try-catch문으로 예외처리를 하지 않은 것이 한가지 아쉬운 점이었습니다😢 
이렇게 비동기 로직을 처리하기 위해 발전해온 JS문법을 시간 순으로 나열해봤습니다. 이미 잘 알고 계시지만 문서와 제 리뷰를 읽어보시고 더 좋은 이해를 하시는 계기가 되었으면 좋겠네요!

이번 미션도 수고하셨습니다!

2024-11-15 08:54 UTC, Indigochi1d commented on src/App.jsx
> +  };
지금은 async/await으로 비동기로직을 처리하고 있네요! 기능은 충분히 잘 수행하고 있으나 예외처리 부분에서 아쉬운 점이 있었어요.

우선 개요부터 말씀드리자면 `async/await` 방식과 `promise 콜백체인(.then()을 이용)` 의 방식은 둘 다 비동기 처리 로직을 위해 사용돼요. async함수로 적용하게 되면 Promise를 반드시 반환하기 때문에 반환값이 Promise객체가 아니더라도 Promise로 감싸서 반환합니다! 이 과정에서 예외처리 로직이 있었다면 더 좋았을 것 같아요.

무조건 정답은 아니지만 제가 자주 사용하는 코드 패턴은 `async/await`을 사용할 때는 `try-catch`를 쓰고 Promise를 쓰게 되면 콜백체인으로 `.then()` 과 `.catch()` 를 통해 예외처리를 하게 돼요. 아래에 코드로 써놓겠습니다! 코드 리뷰 후 적용하고 테스트 해보시면 좋을 것 같아요.
## 1️⃣ async/await + try-catch의 적용
```javascript
const [restaurantsList, setRestaurantsList] = useState([]);

  const getRestaurant = async () => {
    try {
      const response = await fetch('http://localhost:3000/restaurants');
      const jsonData = await response.json();

      if (response.ok) {
        setRestaurantsList([...jsonData]);
      } else {
        console.error('Failed to fetch restaurants:', response.statusText);
      }
    } catch (error) {
      console.error('Error fetching restaurants:', error);
    }
  };

  useEffect(() => {
    getRestaurant();
  }, []);
```
## 2️⃣ Promise의 콜백 체인으로 예외처리하기
```javascript  
const [restaurantsList, setRestaurantsList] = useState([]);

  const getRestaurant = () => {
    fetch('http://localhost:3000/restaurants')
      .then(response => {
        if (!response.ok) {
          throw new Error('Failed to fetch data');
        }
        return response.json();
      })
      .then(jsonData => {
        setRestaurantsList([...jsonData]);
      })
      .catch(error => {
        console.error('Error fetching restaurants:', error);
      });
  };
  useEffect(() => {
    getRestaurant();
  }, []);
```

2024-11-15 08:54 UTC, Indigochi1d commented on src/api/restaurant.jsx
> +};
> -> main과 aside 컴포넌트에 각각 책임을 나누려고 상태랑 함수를 나누고 api를 따로 모듈로 만들었습니다. POST 요청은 정상적으로 작동하는데 GET 요청을 import해서 사용하니, 요청이 안됩니다,, 이유를 찾아보려했는데 못찾아서 그냥 GET 요청은 직접 했습니다..! 혹시 이유를 알고계시다면 알려주시면 감사하겠습니당🥲

이 함수가 import했을때 원하는대로 기능하지 않는군요..! 저도 테스트를 다시 해보고 리뷰적으러 다시 오겠습니다...!

2024-11-15 08:54 UTC, Indigochi1d commented on src/api/restaurant.jsx
> +};
`App.jsx`에서의 리뷰와 마찬가지로 예외처리 로직이 없어서 추가해주시면 좋을 것 같습니다!

이렇게만 사용하신다고 하면 `async`에 대해서 [공식문서](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/async_function)를 한번 더 읽어보시면 좋을 것 같아요. `async`를 사용하면 무조건 프로미스 객체 반환합니다. 따라서 response로 ok를 검증하는게 아니라면 POST 메서드에선 response 변수를 선언하지 않아도 되는게 아닐까요?
아래의 코드와 같이 말이죠.
```javascript
export const postRestaurant = async (newRestaurant) => {
  await fetch('http://localhost:3000/restaurants', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(newRestaurant),
  });
};
```

물론 예외처리 과정에서`response.ok`를 검증해야한다면 response를 선언해야겠지만요!

2024-11-15 08:54 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
>    };
이 곳에서는 예외처리 로직이 필요한지 필요하지 않은지 혜정님의 의견을 들려주세요!👂🏻

2024-11-15 21:50 UTC, Indigochi1d commented on src/api/restaurant.jsx
> +};
저 getRestaurant함수 내에서 setRestaurantsList를 통해 상태를 변경하지 않고 있어서 안되는거 같아보여요. 따라서 props로 setter함수를 보내주어 기능하게 하면 될 것 같아서 해보았더니 잘 되네요!

그래서 저는 이렇게 혜정님의 코드를 수정해봤는데 원하는대로 동작함을 알 수 있었어요.
`api/restaurant.jsx`
```javascript
//restaurant.jsx
export const getRestaurant = async (setRestaurantsList) => {
  const response = await fetch('http://localhost:3000/restaurants');
  const jsonData = await response.json();

  setRestaurantsList(jsonData);
};
// some more codes....
```

`App.jsx`
```javascript
//App.jsx
import {getRestaurant} from "./api/restaurant.jsx";

function App() {
  const [isModalOpen, setIsModalOpen] = useState();
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [selectedRestaurant, setSelectedRestaurant] = useState({
    name: '',
    description: '',
  });
  const [restaurantsList, setRestaurantsList] = useState([]);


  useEffect(() => {
    getRestaurant(setRestaurantsList);
  }, []);

  return (
    <div>
      <Main
        restaurantsList={restaurantsList}
        setIsModalOpen={setIsModalOpen}
        setSelectedRestaurant={setSelectedRestaurant}
        setIsAddModalOpen={setIsAddModalOpen}
      />
      <Aside
        isModalOpen={isModalOpen}
        isAddModalOpen={isAddModalOpen}
        selectedRestaurant={selectedRestaurant}
        setIsModalOpen={setIsModalOpen}
        setIsAddModalOpen={setIsAddModalOpen}
        setRestaurantsList={setRestaurantsList}
      />
    </div>
  );
}
```

`Aside.jsx`
```javascript
//Aside.jsx

function Aside({
  isModalOpen,
  isAddModalOpen,
  selectedRestaurant,
  setIsModalOpen,
  setIsAddModalOpen,
  setRestaurantsList
}) {
  return (
    <aside>
      {isModalOpen && (
        <RestaurantDetailModal
          setIsModalOpen={setIsModalOpen}
          restaurantName={selectedRestaurant.name}
          restaurantDescription={selectedRestaurant.description}
        />
      )}
      {isAddModalOpen && (
        <AddRestaurantModal
          setIsAddModalOpen={setIsAddModalOpen}
          setRestaurantsList={setRestaurantsList}
        />
      )}
    </aside>
  );
}

export default Aside;
```

`AddRestaurantModal`

```javascript
// AddRestaurantModal.jsx
import { postRestaurant,getRestaurant } from '../../api/restaurant';

const AddRestaurantModal = ({ setIsAddModalOpen,setRestaurantsList }) => {
    //some codes...
     const submitFormHandler = async () => {
    const response = await postRestaurant(newRestaurant);

    if (response.ok) {
      await getRestaurant(setRestaurantsList);
      setIsAddModalOpen(false);
    } else {
      console.log(response);
    }
  };
   //some codes...
}
```

이렇게 setter함수를 직접 `App` ➡️ `AddRestaurantModal` 에 전달하고 POST와 동시에 response가 ok라면 GET 메서드를 불러오는 코드로 만들어주었습니다.

혜정님과 제가 고친 코드에서 달랐던 점은 setter함수를 props로 받아 상태로직을 처리했다는 점 밖에 없습니다!

2024-11-18 11:09 UTC, Songhyejeong commented on src/App.jsx
> +  };
저는 예외 처리 하는 걸 습관으로 들이지 않아서 예외처리를 할 때도 있고 안 할 때도 있었던 거 같아요..! 
지난 주 스터디에서도 언급하셨던 것 중에 async await가 Promise 값을 반환한다는 사실을 모르고 있었어요!
범수님이 앞서 작성해주신 설명글 보니 왜 여전히 Promise 값을 반환하는지, 어떻게 처리해야하는지 왜 예외처리를 해야하는지 확실하게 알게 되었습니다 👍 
Promise를 사용할 때는 콜백 체인을 쓰고, async await는 try-catch문을 사용하는 것이 일반적이라는 것도 
새롭게 알게 되었네요! 
자세한 설명 감사합니다~!! 따로 메모해서 두고두고 기억 해야겠어요

2024-11-18 11:28 UTC, Songhyejeong commented on src/api/restaurant.jsx
> +};
헉 그러네요,, 제 코드가 데이터만 반환하고 아무것도 안 하네요..
setter 함수를 인자로 넘겨서 POST 후 바로 GET요청이 되게 할 생각을 못했었는데 생각의 사고를 조금 넓혀봐야겠어요!

2024-11-18 11:54 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
>    };
예외처리(try-catch) 의 역할은 promise에서 reject 된 경우를 처리하고, 
response는 API 요청에서 서버에서 반환해주는 404, 500등 상태의 값을 읽고 response 내용이 원하는 결과가 아닐 때를 처리하는 것이라고 이해를 했는데 그러면  

- response는 에러가 발생했을 때 어떤 에러가 발생했는지 그 값을 알려준다. 
- 예외 처리 로직은 기본적으로 async await에서 반환하는 Promise 값을 처리해서 에러가 발생했을 때 프로그래밍이 비정상적으로 끝나거나 중단되는 것을 막아준다.
이렇게 이해를 하는게 맞을 까요?

제가 이해한 것이 맞다면 response는 예외 처리라고 할 수 없으니 else 값을 추가해주면 올바른 응답 값 이외의 상태들에 대해서 처리 해주기 때문에 예외 처리 로직이 필요 없을 것 같고,

위에 제가 작성한 GET 요청 처럼 `reponse.ok` 값만을 처리 했을 때는 예외 처리 로직을 추가해서 API 요청을 보냈을 때 네트워크 오류나 JSON 에러를 처리하고 프로그램이 중단 되지 않는지 확인하는 로직이 필요할 거 같습니다!

근데 여기서 궁금한게 비동기 함수에서 일반적으로 Promise 값을 반환하니까 if-else 보다는 try-catch문을 사용해서 예외 처리를 하는 것이 더 좋은 방법이겠죠?

2024-11-18 11:54 UTC, Songhyejeong commented on src/api/restaurant.jsx
> +};
넵!

2024-11-18 12:18 UTC, Songhyejeong commented
좋은 리뷰 감사드립니다 ! 확실히 스터디 하면서 항상 애매하게 넘겼던 개념을 바로잡고 갈 수 있어서 좋은 것 같습니다
이번 미션 진행하면서 async await가 Promise 값을 반환하는지 모르고, response가 예외처리를 대신한다고 생각했었는데, response와 예외 처리는 아예 다른 거였더군요. 범수님이 정리 해주신 글 읽고 정리하니 이해가 쉽게 가는것 같습니다! 

결론적으로 response 값으로 어떤 에러가 발생했는지 알게 하고, 예외 처리 로직으로 Promise 값을 처리해준다라고 이해한게 맞는지 궁금하네요..! 자세한건 마지막 답변에 작성했습니다 

감사합니다!

2024-11-18 12:29 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
>    };
맞아요. 사실 `submitFormHandler` 에서는 저라면 예외처리를 하지 않을 것 같아요. 왜냐하면 이미 `postRestaurant` 와 `getRestaurant` 에서 비동기 api 쿼리 로직을 처리할 때 한번 예외처리를 통해 필터링하기 때문이에요. 
혜정님이 말씀해주신대로 try-catch를 통해 예외처리하는 것이 조금 더 좋아보입니다. 왜냐하면 if-else로는 런타임 에러를 잡기 못하기 때문이에요.

런타임 에러를 잡을 수 있다는 말은 파일 읽기 실패, 네트워크 오류 등 "개발자가 코드 입장에서" 예측할 수 없는 케이스들을 try-catch로 잡을 수 있다는 것을 의미해요. 더 많은 내용은 아래의 [문서링크](https://ko.javascript.info/try-catch)를 첨부해놓을테니 학교가는길이나 집으로 가는길에 지하철에서 한번 읽어보시면 좋을 것 같습니다 ㅎ

2024-11-18 12:32 UTC, Indigochi1d commented
저도 혜정님의 답변에 대해서 짤막하게나마 답변해보았습니다! 이번 리뷰를 통해 Promise와 비동기로직에 대해서 이해하실 수 있었다니 너무 다행이네요💯 이번 미션도 고생하셨습니다!

2024-11-18 12:33 UTC, Indigochi1d reviewed
저도 혜정님의 답변에 대해서 짤막하게나마 답변해보았습니다! 이번 리뷰를 통해 Promise와 비동기로직에 대해서 이해하실 수 있었다니 너무 다행이네요💯 이번 미션도 고생하셨습니다!

2024-11-18 12:33 UTC, Indigochi1d commented on src/components/main/main/Main.jsx
> +          setSelectedRestaurant={setSelectedRestaurant}
💯

2024-11-18 12:33 UTC, Indigochi1d commented on src/components/aside/AddRestaurantModal.jsx
> +const AddRestaurantModal = ({ setRestaurantsList, setIsAddModalOpen }) => {
💯

2024-11-18 12:33 UTC, Indigochi1d commented on src/api/restaurant.jsx
> +  }
💯

2024-11-20 02:26 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
>    };
범수님 말씀대로 예측할 수 없는 서버와의 통신 오류를 잡기 위해서 try-catch를 사용해야겠어요! 좋은 자료 감사합니다!

2024-11-20 02:34 UTC, Indigochi1d approved these changes

2024-11-20 02:34 UTC, merged